<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Module 9: Solutions to Learning Activities | PHCM9795 Foundations of Biostatistics</title>
  <meta name="description" content="Module 9: Solutions to Learning Activities | PHCM9795 Foundations of Biostatistics" />
  <meta name="generator" content="bookdown 0.26 and GitBook 2.6.7" />

  <meta property="og:title" content="Module 9: Solutions to Learning Activities | PHCM9795 Foundations of Biostatistics" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Module 9: Solutions to Learning Activities | PHCM9795 Foundations of Biostatistics" />
  
  
  

<meta name="author" content="Learning activity solutions: R version" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="module-8-full-script.html"/>
<link rel="next" href="module-9-full-script.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">PHCM9795 Foundations of Biostatistics - Learning activity solutions</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="" data-path="module-1-solutions-to-learning-activities.html"><a href="module-1-solutions-to-learning-activities.html"><i class="fa fa-check"></i>Module 1: Solutions to Learning Activities</a></li>
<li class="chapter" data-level="" data-path="module-1-full-script.html"><a href="module-1-full-script.html"><i class="fa fa-check"></i>Module 1: Full script</a></li>
<li class="chapter" data-level="" data-path="module-2-solutions-to-learning-activities.html"><a href="module-2-solutions-to-learning-activities.html"><i class="fa fa-check"></i>Module 2: Solutions to Learning Activities</a></li>
<li class="chapter" data-level="" data-path="module-2-full-script.html"><a href="module-2-full-script.html"><i class="fa fa-check"></i>Module 2: Full script</a></li>
<li class="chapter" data-level="" data-path="module-3-solutions-to-learning-activities.html"><a href="module-3-solutions-to-learning-activities.html"><i class="fa fa-check"></i>Module 3: Solutions to Learning Activities</a></li>
<li class="chapter" data-level="" data-path="module-3-full-script.html"><a href="module-3-full-script.html"><i class="fa fa-check"></i>Module 3: Full script</a></li>
<li class="chapter" data-level="" data-path="module-4-solutions-to-learning-activities.html"><a href="module-4-solutions-to-learning-activities.html"><i class="fa fa-check"></i>Module 4: Solutions to Learning Activities</a></li>
<li class="chapter" data-level="" data-path="module-4-full-script.html"><a href="module-4-full-script.html"><i class="fa fa-check"></i>Module 4: Full script</a></li>
<li class="chapter" data-level="" data-path="module-5-solutions-to-learning-activities.html"><a href="module-5-solutions-to-learning-activities.html"><i class="fa fa-check"></i>Module 5: Solutions to Learning Activities</a></li>
<li class="chapter" data-level="" data-path="module-5-full-script.html"><a href="module-5-full-script.html"><i class="fa fa-check"></i>Module 5: Full script</a></li>
<li class="chapter" data-level="" data-path="module-6-solutions-to-learning-activities.html"><a href="module-6-solutions-to-learning-activities.html"><i class="fa fa-check"></i>Module 6: Solutions to Learning Activities</a></li>
<li class="chapter" data-level="" data-path="module-6-full-script.html"><a href="module-6-full-script.html"><i class="fa fa-check"></i>Module 6: Full script</a></li>
<li class="chapter" data-level="" data-path="module-7-solutions-to-learning-activities.html"><a href="module-7-solutions-to-learning-activities.html"><i class="fa fa-check"></i>Module 7: Solutions to Learning Activities</a></li>
<li class="chapter" data-level="" data-path="module-7-full-script.html"><a href="module-7-full-script.html"><i class="fa fa-check"></i>Module 7: Full script</a></li>
<li class="chapter" data-level="" data-path="module-8-solutions-to-learning-activities.html"><a href="module-8-solutions-to-learning-activities.html"><i class="fa fa-check"></i>Module 8: Solutions to Learning Activities</a></li>
<li class="chapter" data-level="" data-path="module-8-full-script.html"><a href="module-8-full-script.html"><i class="fa fa-check"></i>Module 8: Full script</a></li>
<li class="chapter" data-level="" data-path="module-9-solutions-to-learning-activities.html"><a href="module-9-solutions-to-learning-activities.html"><i class="fa fa-check"></i>Module 9: Solutions to Learning Activities</a></li>
<li class="chapter" data-level="" data-path="module-9-full-script.html"><a href="module-9-full-script.html"><i class="fa fa-check"></i>Module 9: Full script</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">PHCM9795 Foundations of Biostatistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="module-9-solutions-to-learning-activities" class="section level1 unnumbered hasAnchor">
<h1>Module 9: Solutions to Learning Activities<a href="module-9-solutions-to-learning-activities.html#module-9-solutions-to-learning-activities" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="activity-9.1" class="section level3 unnumbered hasAnchor">
<h3>Activity 9.1<a href="module-9-solutions-to-learning-activities.html#activity-9.1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>There is a hypothesis that university students who live and dine in the university hall consume less vitamin C than the students who live and dine at home. To test the hypothesis, 30 students were randomly selected and their urinary ascorbic acid level was measured in mg over 3 hours. Urinary excretion of ascorbic acid is a measure of vitamin C nutrition in humans. The data is given as ActivityS9.1.rds.</p>
<ol style="list-style-type: lower-alpha">
<li>Examine the distribution of the data using a box-plot and histogram.</li>
</ol>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb195-1"><a href="module-9-solutions-to-learning-activities.html#cb195-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jmv)</span>
<span id="cb195-2"><a href="module-9-solutions-to-learning-activities.html#cb195-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb195-3"><a href="module-9-solutions-to-learning-activities.html#cb195-3" aria-hidden="true" tabindex="-1"></a>diet <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">&quot;data/activities/Activity_S9.1.rds&quot;</span>)</span>
<span id="cb195-4"><a href="module-9-solutions-to-learning-activities.html#cb195-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb195-5"><a href="module-9-solutions-to-learning-activities.html#cb195-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(diet)</span></code></pre></div>
<pre><code>##                        dint ascorb
## 1 Living and dining in hall      7
## 2 Living and dining at home     22
## 3 Living and dining in hall      9
## 4 Living and dining at home     25
## 5 Living and dining in hall     14
## 6 Living and dining at home     30</code></pre>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="module-9-solutions-to-learning-activities.html#cb197-1" aria-hidden="true" tabindex="-1"></a>hall <span class="ot">&lt;-</span> <span class="fu">subset</span>(diet, dint<span class="sc">==</span><span class="st">&quot;Living and dining in hall&quot;</span>)</span>
<span id="cb197-2"><a href="module-9-solutions-to-learning-activities.html#cb197-2" aria-hidden="true" tabindex="-1"></a>home <span class="ot">&lt;-</span> <span class="fu">subset</span>(diet, dint<span class="sc">==</span><span class="st">&quot;Living and dining at home&quot;</span>)</span>
<span id="cb197-3"><a href="module-9-solutions-to-learning-activities.html#cb197-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb197-4"><a href="module-9-solutions-to-learning-activities.html#cb197-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the graphics parameters to plot 2 rows and 2 columns:</span></span>
<span id="cb197-5"><a href="module-9-solutions-to-learning-activities.html#cb197-5" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb197-6"><a href="module-9-solutions-to-learning-activities.html#cb197-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb197-7"><a href="module-9-solutions-to-learning-activities.html#cb197-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify each plot separately</span></span>
<span id="cb197-8"><a href="module-9-solutions-to-learning-activities.html#cb197-8" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(hall<span class="sc">$</span>ascorb, <span class="at">xlab=</span><span class="st">&quot;Ascorbic acid (mg / 3 hr)&quot;</span>,</span>
<span id="cb197-9"><a href="module-9-solutions-to-learning-activities.html#cb197-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlim=</span><span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">400</span>), <span class="at">main=</span><span class="st">&quot;Living and dining in hall&quot;</span>)</span>
<span id="cb197-10"><a href="module-9-solutions-to-learning-activities.html#cb197-10" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(home<span class="sc">$</span>ascorb, <span class="at">xlab=</span><span class="st">&quot;Ascorbic acid (mg / 3 hr)&quot;</span>, <span class="at">main=</span><span class="st">&quot;Living and dining at home&quot;</span>)</span>
<span id="cb197-11"><a href="module-9-solutions-to-learning-activities.html#cb197-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb197-12"><a href="module-9-solutions-to-learning-activities.html#cb197-12" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(hall<span class="sc">$</span>ascorb, <span class="at">ylab=</span><span class="st">&quot;Ascorbic acid (mg / 3 hr)&quot;</span>, </span>
<span id="cb197-13"><a href="module-9-solutions-to-learning-activities.html#cb197-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">400</span>), <span class="at">main=</span><span class="st">&quot;Living and dining in hall&quot;</span>)</span>
<span id="cb197-14"><a href="module-9-solutions-to-learning-activities.html#cb197-14" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(home<span class="sc">$</span>ascorb, <span class="at">ylab=</span><span class="st">&quot;Ascorbic acid (mg / 3 hr)&quot;</span>, <span class="at">main=</span><span class="st">&quot;Living and dining at home&quot;</span>)</span></code></pre></div>
<p><img src="phcm9795-solutions-R_files/figure-html/unnamed-chunk-87-1.png" width="672" /></p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="module-9-solutions-to-learning-activities.html#cb198-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span></code></pre></div>
<blockquote>
<p>By examining the box plots and histograms we can say that ascorbic acid data for both of the student groups are highly positively skewed as well as highly peaked with some outliers that are biologically plausible.</p>
</blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li>Which statistical test would be appropriate to test the hypothesis mentioned in the question and why?</li>
</ol>
<blockquote>
<p>Following the decision tree, the response variable is continuous (concentration of urinary ascorbic acid) and the explanatory variable is categorical (residential and dining status of the students) with two groups (binary). The two groups are independent as students either live at home or at university, not both. As evident from (a) the distribution of the response variable for both of the groups is highly positively skewed and peaked. Therefore, a distribution free (non-parametric) test would be appropriate to analyse the data. Because the distribution of both of the groups (Hall and Home) are positively skewed, that is they are of the same shape, the Wilcoxon rank-sum test would be appropriate to test the difference in medians.</p>
</blockquote>
<ol start="3" style="list-style-type: lower-alpha">
<li>State the hypothesis appropriate to the analytical method you mentioned in (b)?</li>
</ol>
<blockquote>
<p>Null hypothesis: The median concentration of urinary ascorbic acid among the students who live and dine in the university hall is the same as that of the students who live and dine at home.
Alternative hypothesis: The median concentration of urinary ascorbic acid among the students who live and dine in the university hall is not same as that of the students who live and dine at home.</p>
</blockquote>
<ol start="4" style="list-style-type: lower-alpha">
<li>Use R to carry out the statistical test you have mentioned in (b) and write your conclusion.</li>
</ol>
<blockquote>
<p>We can use the <code>wilcox.test()</code> function to carry out the Wilcoxon rank-sum test.</p>
</blockquote>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="module-9-solutions-to-learning-activities.html#cb199-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(ascorb <span class="sc">~</span> dint, <span class="at">data=</span>diet)</span></code></pre></div>
<pre><code>## Warning in wilcox.test.default(x = c(7, 9, 14, 16, 20, 22, 27, 28, 28, 34, :
## cannot compute exact p-value with ties</code></pre>
<pre><code>## 
##  Wilcoxon rank sum test with continuity correction
## 
## data:  ascorb by dint
## W = 45.5, p-value = 0.006927
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<blockquote>
<p>The P-value from the test is 0.007, which indicates that there is strong evidence of a difference between the median values of urinary ascorbic acid between the two student groups. The Wilcoxon rank-sum test does not report median values of the individual groups as part of the output. To include median values in the conclusion, we need to run the <code>descriptives()</code> command as shown below.</p>
</blockquote>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb202-1"><a href="module-9-solutions-to-learning-activities.html#cb202-1" aria-hidden="true" tabindex="-1"></a><span class="fu">descriptives</span>(<span class="at">data=</span>diet, <span class="at">vars=</span>ascorb, <span class="at">splitBy =</span> dint,</span>
<span id="cb202-2"><a href="module-9-solutions-to-learning-activities.html#cb202-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">pc=</span><span class="cn">TRUE</span>)   </span></code></pre></div>
<pre><code>## 
##  DESCRIPTIVES
## 
##  Descriptives                                                    
##  ─────────────────────────────────────────────────────────────── 
##                          dint                         ascorb     
##  ─────────────────────────────────────────────────────────────── 
##    N                     Living and dining in hall          17   
##                          Living and dining at home          13   
##    Missing               Living and dining in hall           0   
##                          Living and dining at home           0   
##    Mean                  Living and dining in hall    36.64706   
##                          Living and dining at home    114.2308   
##    Median                Living and dining in hall    28.00000   
##                          Living and dining at home    83.00000   
##    Standard deviation    Living and dining in hall    27.91044   
##                          Living and dining at home    106.2302   
##    Minimum               Living and dining in hall    7.000000   
##                          Living and dining at home    22.00000   
##    Maximum               Living and dining in hall    121.0000   
##                          Living and dining at home    372.0000   
##    25th percentile       Living and dining in hall    20.00000   
##                          Living and dining at home    47.00000   
##    50th percentile       Living and dining in hall    28.00000   
##                          Living and dining at home    83.00000   
##    75th percentile       Living and dining in hall    38.00000   
##                          Living and dining at home    163.0000   
##  ───────────────────────────────────────────────────────────────</code></pre>
<blockquote>
<p><strong>Conclusion:</strong> There is strong evidence from Mann-Whitney U test (exact P = 0.007) that the median concentration of urinary ascorbic acid among the university students who live and dine at home (83 mg per 3 hours, interquartile range: 47 to 163) is higher than that of the students who live and dine in the university hall (28 mg per 3 hours, interquartile range: 20 to 38).</p>
</blockquote>
</div>
<div id="activity-9.2" class="section level3 unnumbered hasAnchor">
<h3>Activity 9.2<a href="module-9-solutions-to-learning-activities.html#activity-9.2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A drug was tested for its effect in lowering blood pressure. Fifteen women with hypertension were enrolled and had their systolic blood pressure measured before and after taking the drug. The data are available in the file Activity_S9.2.rds on Moodle.</p>
<ol style="list-style-type: lower-alpha">
<li>State the research question and the null hypothesis.</li>
</ol>
<blockquote>
<p>Research question: Do women with hypertension have lower systolic blood pressure after taking the test drug than before taking the drug?</p>
</blockquote>
<blockquote>
<p>Null hypothesis: There is no change in median systolic blood pressure before and after taking the drug.</p>
</blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li>Use R to obtain suitable summary statistics and test the null hypothesis. Describe the reason for choosing the test.</li>
</ol>
<blockquote>
<p>Systolic blood pressure was measured for each person twice to compare the difference in blood pressure before and after taking the drug. Therefore, the study is a paired design and, because blood pressure is a continuous measurement, a paired t-test can be considered. One of the assumptions of a paired t-test is that the differences between the measurements are normally distributed and this needs to be checked.</p>
</blockquote>
<blockquote>
<p>To check the distribution of the differences between the measurements, we first need to calculate the differences. We created a new variable ‘difference’ using the equation ‘BP_After_mmHg − BP_Before_mmHg’. The histogram of the differences is shown in Figure 2.</p>
</blockquote>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="module-9-solutions-to-learning-activities.html#cb204-1" aria-hidden="true" tabindex="-1"></a>bp <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">&quot;data/activities/Activity_S9.2.rds&quot;</span>)</span>
<span id="cb204-2"><a href="module-9-solutions-to-learning-activities.html#cb204-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(bp)</span></code></pre></div>
<pre><code>##   id bp_before_mmhg bp_after_mmhg difference
## 1  1            143           120        -23
## 2  2            150           124        -26
## 3  3            140           130        -10
## 4  4            139           118        -21
## 5  5            141           140         -1
## 6  6            144           128        -16</code></pre>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb206-1"><a href="module-9-solutions-to-learning-activities.html#cb206-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(bp<span class="sc">$</span>difference,</span>
<span id="cb206-2"><a href="module-9-solutions-to-learning-activities.html#cb206-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Figure 2: Reduction in blood pressure after taking a new drug&quot;</span>,</span>
<span id="cb206-3"><a href="module-9-solutions-to-learning-activities.html#cb206-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Difference (mmHg)&quot;</span>)</span></code></pre></div>
<p><img src="phcm9795-solutions-R_files/figure-html/unnamed-chunk-90-1.png" width="672" /></p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb207-1"><a href="module-9-solutions-to-learning-activities.html#cb207-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Note - histogram differs from Stata, as R uses intervals as (a, b], where as Stata uses [a, b).</span></span></code></pre></div>
<blockquote>
<p>The histogram of the differences (BP_After – BP_Before) does not approximate a normal distribution. Therefore, the paired t-test is not appropriate and its non-parametric equivalent, the Wilcoxon signed rank test, should be considered.
The Wilcoxon signed rank test is obtained using the <code>wilcox.test()</code> function:</p>
</blockquote>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="module-9-solutions-to-learning-activities.html#cb208-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(bp<span class="sc">$</span>bp_before_mmhg, bp<span class="sc">$</span>bp_after_mmhg, <span class="at">paired=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Warning in wilcox.test.default(bp$bp_before_mmhg, bp$bp_after_mmhg, paired =
## TRUE): cannot compute exact p-value with ties</code></pre>
<pre><code>## 
##  Wilcoxon signed rank test with continuity correction
## 
## data:  bp$bp_before_mmhg and bp$bp_after_mmhg
## V = 120, p-value = 0.0007158
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<ol start="3" style="list-style-type: lower-alpha">
<li>Write a brief conclusion.</li>
</ol>
<blockquote>
<p>To include descriptive summary statistics in our conclusion we need to obtain summary statistics of the blood pressure measurements before and after taking the drug and the differences between these two measurements.</p>
</blockquote>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="module-9-solutions-to-learning-activities.html#cb211-1" aria-hidden="true" tabindex="-1"></a><span class="fu">descriptives</span>(<span class="at">data=</span>bp, <span class="at">vars=</span><span class="fu">c</span>(bp_before_mmhg, bp_after_mmhg, difference),</span>
<span id="cb211-2"><a href="module-9-solutions-to-learning-activities.html#cb211-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">pc=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  DESCRIPTIVES
## 
##  Descriptives                                                            
##  ─────────────────────────────────────────────────────────────────────── 
##                          bp_before_mmhg    bp_after_mmhg    difference   
##  ─────────────────────────────────────────────────────────────────────── 
##    N                                 15               15            15   
##    Missing                            0                0             0   
##    Mean                        146.4667         129.2667     -17.20000   
##    Median                      144.0000         128.0000     -16.00000   
##    Standard deviation          10.75617         6.902036      13.41215   
##    Minimum                     139.0000         118.0000     -57.00000   
##    Maximum                     183.0000         140.0000     -1.000000   
##    25th percentile             140.5000         125.5000     -21.00000   
##    50th percentile             144.0000         128.0000     -16.00000   
##    75th percentile             146.5000         132.5000     -8.000000   
##  ───────────────────────────────────────────────────────────────────────</code></pre>
<blockquote>
<p>The median (IQR) SBP before and after taking the drug was 144 (140 to 147) mmHg and 128 (125 to 135) mmHg, respectively. The median (IQR) reduction in SBP is 16 (6 to 21) mmHg. There is very strong evidence that the drug lowered blood pressure in this group of hypertensive women (Wilcoxon P = 0.0007).</p>
</blockquote>
<ol start="4" style="list-style-type: lower-alpha">
<li>What are the main limitations of this study? Consider both epidemiological and statistical aspects.</li>
</ol>
<blockquote>
<p>The samples were selected from a small patient group with particular characteristics (hypertensive females). While the results may be generalisable to hypertensive women in the population, assuming the sample is representative of hypertensive women in the population, the results may not be applicable to men. The strongest weakness is that there is no control group; the blood pressure in the women may have in fact lowered in the absence of taking the drug. This could be avoided by conducting a randomised controlled trial.</p>
</blockquote>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="module-8-full-script.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="module-9-full-script.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["phcm9795-solutions-R.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
