% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{memoir}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
  \setmainfont[]{Roboto}
  \setsansfont[]{Clancy}
  \setmonofont[Scale=0.9]{Roboto Mono}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={PHCM9795 Foundations of Biostatistics},
  pdfauthor={Learning activity solutions: R version},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{booktabs}
\usepackage{float}

\floatstyle{boxed}
\newfloat{program}{thp}{lop}
\floatname{program}{Output}

\renewcommand{\chaptername}{Module}
\renewcommand*{\chapnamefont}{\normalfont\HUGE\bfseries\sffamily}
\renewcommand*{\chapnumfont}{\normalfont\HUGE\bfseries\sffamily}
\renewcommand*{\chaptitlefont}{\normalfont\HUGE\bfseries\sffamily}

\setsecheadstyle{\sffamily}% Set \section style
\setsubsecheadstyle{\sffamily}% Set \subsection style
\setsubsubsecheadstyle{\sffamily}% Set \subsubsection style

\setlrmarginsandblock{3.5cm}{2.5cm}{*}
\setulmarginsandblock{2.5cm}{*}{1}
\checkandfixthelayout 

\raggedright
\raggedbottom
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage[]{natbib}
\bibliographystyle{plainnat}

\title{PHCM9795 Foundations of Biostatistics}
\author{Learning activity solutions: R version}
\date{14 June, 2022}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{1}
\tableofcontents
}
\hypertarget{introduction}{%
\chapter*{Introduction}\label{introduction}}
\addcontentsline{toc}{chapter}{Introduction}

These notes provide R-based solutions to the learning activities in Foundations of Biostatistics.

These notes are currently under development, with sections being added and revised as the course progresses.

This is the first year that R has been offered as an option. I am keen to receive feedback about the notes and your experience learning R. Please \href{mailto:t.dobbins@unsw.edu.au}{get in touch} if anything is unclear, or you have any questions or suggestions.

\hypertarget{changelog}{%
\subsection*{Changelog}\label{changelog}}
\addcontentsline{toc}{subsection}{Changelog}

\textbf{2022-06-12}
{[}Added{]}

\begin{itemize}
\tightlist
\item
  Module 3: Initial release
\item
  Module 4: Initial release
\end{itemize}

\textbf{2022-06-06}
{[}Added{]}

\begin{itemize}
\tightlist
\item
  Module 2: Initial release
\end{itemize}

{[}Changed{]}

\begin{itemize}
\tightlist
\item
  Various typos
\end{itemize}

\textbf{2022-05-30}

{[}Added{]}

\begin{itemize}
\tightlist
\item
  Module 1: Initial release
\end{itemize}

\hypertarget{module-1-solutions-to-learning-activities}{%
\chapter*{Module 1: Solutions to Learning Activities}\label{module-1-solutions-to-learning-activities}}
\addcontentsline{toc}{chapter}{Module 1: Solutions to Learning Activities}

\hypertarget{activity-1.1}{%
\subsection*{Activity 1.1}\label{activity-1.1}}
\addcontentsline{toc}{subsection}{Activity 1.1}

25 participants were enrolled in a 3-week weight loss programme. The following data present the weight loss (in grams) of the participants:

\begin{verbatim}
   255   198   283   312   283
   57    85    312   142   113
   227   283   255   340   142
   113   312   227    85   170
   255   198   113   227   255
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
  Enter these data into R.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{weightloss }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{255}\NormalTok{, }\DecValTok{198}\NormalTok{, }\DecValTok{283}\NormalTok{, }\DecValTok{312}\NormalTok{, }\DecValTok{283}\NormalTok{, }\DecValTok{57}\NormalTok{,  }\DecValTok{85}\NormalTok{, }\DecValTok{312}\NormalTok{, }\DecValTok{142}\NormalTok{, }\DecValTok{113}\NormalTok{,}
                \DecValTok{227}\NormalTok{, }\DecValTok{283}\NormalTok{, }\DecValTok{255}\NormalTok{, }\DecValTok{340}\NormalTok{, }\DecValTok{142}\NormalTok{, }\DecValTok{113}\NormalTok{, }\DecValTok{312}\NormalTok{, }\DecValTok{227}\NormalTok{,  }\DecValTok{85}\NormalTok{, }\DecValTok{170}\NormalTok{,}
                \DecValTok{255}\NormalTok{, }\DecValTok{198}\NormalTok{, }\DecValTok{113}\NormalTok{, }\DecValTok{227}\NormalTok{, }\DecValTok{255}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  What type of data are these?
\end{enumerate}

\begin{quote}
These are continuous numeric data.
\end{quote}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  Construct an appropriate graph to display the relative frequency of participants' weight loss. Your graph should start at 50 grams, with weight loss grouped into 50 gram bins. Provide appropriate labels for the axes and give the graph an appropriate title.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Check the default histogram:}
\FunctionTok{hist}\NormalTok{(weightloss)}
\end{Highlighting}
\end{Shaded}

\includegraphics{phcm9795-solutions-R_files/figure-latex/unnamed-chunk-3-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# The default values look ok, so let\textquotesingle{}s add labels and titles}
\FunctionTok{hist}\NormalTok{(weightloss, }\AttributeTok{xlab=}\StringTok{"Weight loss (g)"}\NormalTok{, }\AttributeTok{main=}\StringTok{"Weight loss for 25 participants"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{phcm9795-solutions-R_files/figure-latex/unnamed-chunk-3-2.pdf}

Note that the question requests \textbf{relative frequencies}, so we can use the code in Section 1.12 to amend this graph:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{h }\OtherTok{\textless{}{-}} \FunctionTok{hist}\NormalTok{(weightloss, }\AttributeTok{plot=}\ConstantTok{FALSE}\NormalTok{)}
\NormalTok{h}\SpecialCharTok{$}\NormalTok{density }\OtherTok{\textless{}{-}}\NormalTok{ h}\SpecialCharTok{$}\NormalTok{counts}\SpecialCharTok{/}\FunctionTok{sum}\NormalTok{(h}\SpecialCharTok{$}\NormalTok{counts)}\SpecialCharTok{*}\DecValTok{100}
\FunctionTok{plot}\NormalTok{(h, }\AttributeTok{freq=}\ConstantTok{FALSE}\NormalTok{, }
     \AttributeTok{xlab=}\StringTok{"Weight loss (g)"}\NormalTok{, }
     \AttributeTok{ylab=}\StringTok{"Relative frequency (\%)"}\NormalTok{,}
     \AttributeTok{main=}\StringTok{"Fig 1.1: Weight loss for 25 participants"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{phcm9795-solutions-R_files/figure-latex/unnamed-chunk-4-1.pdf}

\hypertarget{activity-1.2}{%
\subsection*{Activity 1.2}\label{activity-1.2}}
\addcontentsline{toc}{subsection}{Activity 1.2}

Researchers at a maternity hospital in the 1970s conducted a study of low birth weight babies. Low birth weight is classified as a weight of 2,500g or less at birth. Data were collected on age and smoking status of mothers and the birth weight of their babies. The file \texttt{Activity\_S1.2.rds} contains data on the participants in the study. The file is located on Moodle in the Learning Activities section.

Use R to create a 2 by 2 table to show the proportions of low birth weight babies born to mothers who smoked during pregnancy and those that did not smoke during pregnancy.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(jmv)}

\NormalTok{babies }\OtherTok{\textless{}{-}}\FunctionTok{readRDS}\NormalTok{(}\StringTok{"data/activities/Activity\_S1.2.rds"}\NormalTok{)}

\CommentTok{\# Examine the first six rows of data}
\FunctionTok{head}\NormalTok{(babies)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   AGE    AgeGrp  BWT                 LOW SMOKE
## 1  14 <20 years 2466    Low birth weight   Yes
## 2  14 <20 years 2495    Low birth weight    No
## 3  14 <20 years 3941 Normal birth weight    No
## 4  15 <20 years 2353    Low birth weight    No
## 5  15 <20 years 2381    Low birth weight    No
## 6  15 <20 years 2778 Normal birth weight    No
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Create a two{-}way table showing row percents}
\FunctionTok{contTables}\NormalTok{(}\AttributeTok{data=}\NormalTok{babies, }\AttributeTok{rows=}\NormalTok{SMOKE, }\AttributeTok{cols=}\NormalTok{LOW, }\AttributeTok{pcRow=}\ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  CONTINGENCY TABLES
## 
##  Contingency Tables                                                                
##  ───────────────────────────────────────────────────────────────────────────────── 
##    SMOKE                    Low birth weight    Normal birth weight    Total       
##  ───────────────────────────────────────────────────────────────────────────────── 
##    Yes      Observed                      30                     44           74   
##             % within row            40.54054               59.45946    100.00000   
##                                                                                    
##    No       Observed                      29                     86          115   
##             % within row            25.21739               74.78261    100.00000   
##                                                                                    
##    Total    Observed                      59                    130          189   
##             % within row            31.21693               68.78307    100.00000   
##  ───────────────────────────────────────────────────────────────────────────────── 
## 
## 
##  χ² Tests                              
##  ───────────────────────────────────── 
##          Value       df    p           
##  ───────────────────────────────────── 
##    χ²    4.923705     1    0.0264906   
##    N          189                      
##  ─────────────────────────────────────
\end{verbatim}

Answer the following questions:

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
  What was the total number of mothers who smoked during pregnancy?
\end{enumerate}

\begin{quote}
There were 74 mothers who smoked during pregancy.
\end{quote}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  What proportion of mothers who smoked gave birth to low birth weight babies? What proportion of non-smoking mothers gave birth to low birth weight babies?
\end{enumerate}

\begin{quote}
41\% of mothers who smoked and 25\% of non-smoking mothers gave birth to low birth weight babies.
\end{quote}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  Use R to construct a stacked bar chart of the data to examine if there a difference in the proportion of babies born with a low birth weight in relation to mother's age? Provide appropriate labels for the axes and give the graph an appropriate title.
\end{enumerate}

\begin{quote}
We follow the instructions for creating a stacked bar chart in Module 1. First we create a table of low birth weight by mothers' age-group, and create a stacked bar chart (to check that we're on the right track):
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{counts }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(babies}\SpecialCharTok{$}\NormalTok{LOW, babies}\SpecialCharTok{$}\NormalTok{AgeGrp)}
\NormalTok{counts}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                      
##                       <20 years 20-24 years 25-29 years 30-34 years
##   Low birth weight           15          25          15           4
##   Normal birth weight        36          44          27          18
##                      
##                       35 or more years
##   Low birth weight                   0
##   Normal birth weight                5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{barplot}\NormalTok{(counts, }
        \AttributeTok{main=}\StringTok{"Fig 1.2: Frequency of low birth weight by mother\textquotesingle{}s age group"}\NormalTok{,}
        \AttributeTok{legend =} \FunctionTok{rownames}\NormalTok{(counts), }\AttributeTok{beside=}\ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{phcm9795-solutions-R_files/figure-latex/unnamed-chunk-7-1.pdf}

\begin{quote}
We then calculate the \emph{relative frequency} of low-birth weight by mothers' age group
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{percent }\OtherTok{\textless{}{-}} \FunctionTok{prop.table}\NormalTok{(counts, }\AttributeTok{margin=}\DecValTok{2}\NormalTok{)}\SpecialCharTok{*}\DecValTok{100}
\NormalTok{percent}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                      
##                       <20 years 20-24 years 25-29 years 30-34 years
##   Low birth weight     29.41176    36.23188    35.71429    18.18182
##   Normal birth weight  70.58824    63.76812    64.28571    81.81818
##                      
##                       35 or more years
##   Low birth weight             0.00000
##   Normal birth weight        100.00000
\end{verbatim}

\begin{quote}
and use the \texttt{barplot()} command, as per the notes:
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{barplot}\NormalTok{(percent, }
        \AttributeTok{main=}\StringTok{"Fig 1.3: Relative frequency of low birth weight by mother\textquotesingle{}s age group"}\NormalTok{,}
        \AttributeTok{legend =} \FunctionTok{rownames}\NormalTok{(percent), }\AttributeTok{beside=}\ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{phcm9795-solutions-R_files/figure-latex/unnamed-chunk-9-1.pdf}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{3}
\tightlist
\item
  Using your answers to the question a) and b), write a brief conclusion about the relationship of low birth weight and mother's age and smoking status.
\end{enumerate}

\begin{quote}
In the study, the greatest number of babies were born to mothers in the 20-24 years age group, with the number of babies born declining with increasing maternal age for mothers older than 20-24 years (Figure 1.2). A larger proportion of mothers in the \textless20 years, 20-24 years and 25-29 years age groups gave birth to low birth weight babies compared to mothers aged 30-34 years. No low birth weight babies were born to mothers aged 35 or more (Figure 1.3).
\end{quote}

\begin{quote}
A larger proportion of mothers who smoked during pregnancy gave birth to low birth weight babies compared to mothers who did not smoke during pregnancy.
\end{quote}

\begin{quote}
NB: You will revisit two-way tables in Module 7 where you will conduct statistical tests to determine if the proportions are statistically different to each other.
\end{quote}

\textbf{Note: } Coding graphs, particularly clustered and stacked bar graphs can be difficult! The site \url{https://r-graph-gallery.com/} gives excellent instructions on constructing different types of graphs in R.

\hypertarget{activity-1.3}{%
\subsection*{Activity 1.3}\label{activity-1.3}}
\addcontentsline{toc}{subsection}{Activity 1.3}

Using R, estimate the mean, median, mode, standard deviation, range and interquartile range for the data Activity\_S1.3.rds, available on Moodle.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{act1\_3 }\OtherTok{\textless{}{-}} \FunctionTok{readRDS}\NormalTok{(}\StringTok{"data/activities/Activity\_S1.3.rds"}\NormalTok{)}

\FunctionTok{descriptives}\NormalTok{(act1\_3, }\AttributeTok{mode=}\ConstantTok{TRUE}\NormalTok{, }\AttributeTok{iqr=}\ConstantTok{TRUE}\NormalTok{, }\AttributeTok{pc=}\ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  DESCRIPTIVES
## 
##  Descriptives                         
##  ──────────────────────────────────── 
##                          Lead_concn   
##  ──────────────────────────────────── 
##    N                             15   
##    Missing                        0   
##    Mean                    1.500000   
##    Median                  1.500000   
##    Mode                    1.900000   
##    Standard deviation     0.8434623   
##    IQR                    1.0000000   
##    Minimum                0.1000000   
##    Maximum                 3.200000   
##    25th percentile        0.9500000   
##    50th percentile         1.500000   
##    75th percentile         1.950000   
##  ────────────────────────────────────
\end{verbatim}

\begin{quote}
We can use the \texttt{descriptives()} function to obtain summary statistics. Examining the help entry for \texttt{descriptives()} shows we can request the mode using \texttt{mode=TRUE}, the interquartile range using \texttt{iqr=TRUE} and the percentiles (by default, the quartiles) using \texttt{pc=TRUE}.
The mean is estimated as 1.50, the median is 1.5 and the mode is 1.9. The standard deviation is estimated as 0.843, the range is from 0.1 to 3.2, and the inter-quartile range is from 1.0 to 2.0 (both rounded to 1 decimal place).
\end{quote}

\begin{quote}
Note: no units were provided for the data used in this question. Summary statistics must be presented with their units where the units are available.
\end{quote}

\hypertarget{activity-1.4}{%
\subsection*{Activity 1.4}\label{activity-1.4}}
\addcontentsline{toc}{subsection}{Activity 1.4}

Data of diastolic blood pressure (BP) of a sample of study participants are provided in the dataset Activity\_S1.4.rds. Compute the mean, median, range and SD of diastolic BP.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{act1\_4 }\OtherTok{\textless{}{-}} \FunctionTok{readRDS}\NormalTok{(}\StringTok{"data/activities/Activity\_S1.4.rds"}\NormalTok{)}

\FunctionTok{descriptives}\NormalTok{(act1\_4)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  DESCRIPTIVES
## 
##  Descriptives                       
##  ────────────────────────────────── 
##                          diabp      
##  ────────────────────────────────── 
##    N                          100   
##    Missing                      0   
##    Mean                  82.23000   
##    Median                83.00000   
##    Standard deviation    13.01522   
##    Minimum               56.00000   
##    Maximum               118.0000   
##  ──────────────────────────────────
\end{verbatim}

\begin{quote}
The mean is 82.2 mmHg and the median is 83.0 mmHg. The range is 56.0 to 118.0 mmHg (62.0 mmHg) and the standard deviation is 13.02 mmHg.
\end{quote}

\begin{quote}
\emph{Note that the original data have one decimal place, so we can report the median with one decimal place. Although we are justified in presenting the mean to two decimal places (1 extra than the original data), and the standard deviation with three decimal places (1 more than the mean), there is little to be gained in this level of precision when presenting summary statistics for blood pressure.}
\end{quote}

\hypertarget{activity-1.5}{%
\subsection*{Activity 1.5}\label{activity-1.5}}
\addcontentsline{toc}{subsection}{Activity 1.5}

In a study of 100 participants data were missing for 5 people. The missing data points were coded as `99'. The mean of the data was estimated as 45.0 with a standard deviation of 5.6; the smallest and greatest values are 16 and 65 respectively.

If the researcher analysed the data as if the 99s were real data, would it make the following statistics larger, smaller, or stay the same?

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
  Mean
\end{enumerate}

\begin{quote}
The mean will be larger.
\end{quote}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  Standard Deviation
\end{enumerate}

\begin{quote}
The standard deviation will be larger.
\end{quote}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  Range
\end{enumerate}

\begin{quote}
The range will be larger. The smallest value is still 16, but the largest is 99, and so the range is 99 − 16 = 83.
\end{quote}

\hypertarget{activity-1.6}{%
\subsection*{Activity 1.6}\label{activity-1.6}}
\addcontentsline{toc}{subsection}{Activity 1.6}

Which of the following statements are true? The more dispersed, or spread out, a set of observations are:

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
  The smaller the mean value
\end{enumerate}

\begin{quote}
This is not true because the mean is not influenced by the spread of the values (if the distribution is symmetrical around the mean value)
\end{quote}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  The larger the standard deviation
\end{enumerate}

\begin{quote}
This is true. The larger the spread, the larger the deviations from the mean. Hence the standard deviation will be larger.
\end{quote}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  The smaller the variance
\end{enumerate}

\begin{quote}
This is not true. The variance will be larger if the deviations from the mean are larger.
\end{quote}

\hypertarget{activity-1.7}{%
\subsection*{Activity 1.7}\label{activity-1.7}}
\addcontentsline{toc}{subsection}{Activity 1.7}

If the variance for a set of scores is equal to 9, what is the standard deviation?

\begin{quote}
SD = \(\sqrt{variance} = \sqrt{9} = 3\).
\end{quote}

\hypertarget{module-1-full-script}{%
\chapter*{Module 1: Full script}\label{module-1-full-script}}
\addcontentsline{toc}{chapter}{Module 1: Full script}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Author: Timothy Dobbins}
\CommentTok{\# Date: May, 2022}
\CommentTok{\# Purpose: Learning activities for Module 1}

\FunctionTok{library}\NormalTok{(jmv)}

\DocumentationTok{\#\#\# Activity 1.1}

\NormalTok{weightloss }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{255}\NormalTok{, }\DecValTok{198}\NormalTok{, }\DecValTok{283}\NormalTok{, }\DecValTok{312}\NormalTok{, }\DecValTok{283}\NormalTok{, }\DecValTok{57}\NormalTok{,  }\DecValTok{85}\NormalTok{, }\DecValTok{312}\NormalTok{, }\DecValTok{142}\NormalTok{, }\DecValTok{113}\NormalTok{,}
                \DecValTok{227}\NormalTok{, }\DecValTok{283}\NormalTok{, }\DecValTok{255}\NormalTok{, }\DecValTok{340}\NormalTok{, }\DecValTok{142}\NormalTok{, }\DecValTok{113}\NormalTok{, }\DecValTok{312}\NormalTok{, }\DecValTok{227}\NormalTok{,  }\DecValTok{85}\NormalTok{, }\DecValTok{170}\NormalTok{,}
                \DecValTok{255}\NormalTok{, }\DecValTok{198}\NormalTok{, }\DecValTok{113}\NormalTok{, }\DecValTok{227}\NormalTok{, }\DecValTok{255}\NormalTok{)}
\CommentTok{\# Check the default histogram:}
\FunctionTok{hist}\NormalTok{(weightloss)}

\CommentTok{\# The default values look ok, so let\textquotesingle{}s add labels and titles}
\FunctionTok{hist}\NormalTok{(weightloss, }\AttributeTok{xlab=}\StringTok{"Weight loss (g)"}\NormalTok{, }\AttributeTok{main=}\StringTok{"Weight loss for 25 participants"}\NormalTok{)}

\CommentTok{\# Construct a relative frequency histogram}
\NormalTok{h }\OtherTok{\textless{}{-}} \FunctionTok{hist}\NormalTok{(weightloss, }\AttributeTok{plot=}\ConstantTok{FALSE}\NormalTok{)}
\NormalTok{h}\SpecialCharTok{$}\NormalTok{density }\OtherTok{\textless{}{-}}\NormalTok{ h}\SpecialCharTok{$}\NormalTok{counts}\SpecialCharTok{/}\FunctionTok{sum}\NormalTok{(h}\SpecialCharTok{$}\NormalTok{counts)}\SpecialCharTok{*}\DecValTok{100}
\FunctionTok{plot}\NormalTok{(h, }\AttributeTok{freq=}\ConstantTok{FALSE}\NormalTok{, }
     \AttributeTok{xlab=}\StringTok{"Weight loss (g)"}\NormalTok{, }
     \AttributeTok{ylab=}\StringTok{"Relative frequency (\%)"}\NormalTok{,}
     \AttributeTok{main=}\StringTok{"Fig 1.1: Weight loss for 25 participants"}\NormalTok{)}


\DocumentationTok{\#\#\# Activity 1.2}
\NormalTok{babies }\OtherTok{\textless{}{-}}\FunctionTok{readRDS}\NormalTok{(}\StringTok{"data/activities/Activity\_S1.2.rds"}\NormalTok{)}

\CommentTok{\# Examine the first six rows of data}
\FunctionTok{head}\NormalTok{(babies)}

\CommentTok{\# Create a two{-}way table showing row percents}
\FunctionTok{contTables}\NormalTok{(}\AttributeTok{data=}\NormalTok{babies, }\AttributeTok{rows=}\NormalTok{SMOKE, }\AttributeTok{cols=}\NormalTok{LOW, }\AttributeTok{pcRow=}\ConstantTok{TRUE}\NormalTok{)}

\CommentTok{\# Construct bar charts}
\NormalTok{counts }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(babies}\SpecialCharTok{$}\NormalTok{LOW, babies}\SpecialCharTok{$}\NormalTok{AgeGrp)}
\NormalTok{counts}

\FunctionTok{barplot}\NormalTok{(counts, }
        \AttributeTok{main=}\StringTok{"Fig 1.2: Frequency of low birt weight by mother\textquotesingle{}s age group"}\NormalTok{,}
        \AttributeTok{legend =} \FunctionTok{rownames}\NormalTok{(counts), }\AttributeTok{beside=}\ConstantTok{FALSE}\NormalTok{)}

\NormalTok{percent }\OtherTok{\textless{}{-}} \FunctionTok{prop.table}\NormalTok{(counts, }\AttributeTok{margin=}\DecValTok{2}\NormalTok{)}\SpecialCharTok{*}\DecValTok{100}
\NormalTok{percent}

\FunctionTok{barplot}\NormalTok{(percent, }
        \AttributeTok{main=}\StringTok{"Fig 1.3: Relative frequency of low birth weight by mother\textquotesingle{}s age group"}\NormalTok{,}
        \AttributeTok{legend =} \FunctionTok{rownames}\NormalTok{(percent), }\AttributeTok{beside=}\ConstantTok{FALSE}\NormalTok{)}


\DocumentationTok{\#\#\# Activity 1.3}

\NormalTok{act1\_3 }\OtherTok{\textless{}{-}} \FunctionTok{readRDS}\NormalTok{(}\StringTok{"data/activities/Activity\_S1.3.rds"}\NormalTok{)}

\FunctionTok{descriptives}\NormalTok{(act1\_3, }\AttributeTok{mode=}\ConstantTok{TRUE}\NormalTok{, }\AttributeTok{iqr=}\ConstantTok{TRUE}\NormalTok{, }\AttributeTok{pc=}\ConstantTok{TRUE}\NormalTok{)}


\DocumentationTok{\#\#\# Activity 1.4}

\NormalTok{act1\_4 }\OtherTok{\textless{}{-}} \FunctionTok{readRDS}\NormalTok{(}\StringTok{"data/activities/Activity\_S1.4.rds"}\NormalTok{)}

\FunctionTok{descriptives}\NormalTok{(act1\_4)}
\end{Highlighting}
\end{Shaded}

\hypertarget{module-2-solutions-to-learning-activities}{%
\chapter*{Module 2: Solutions to Learning Activities}\label{module-2-solutions-to-learning-activities}}
\addcontentsline{toc}{chapter}{Module 2: Solutions to Learning Activities}

\hypertarget{activity-2.1}{%
\subsection*{Activity 2.1}\label{activity-2.1}}
\addcontentsline{toc}{subsection}{Activity 2.1}

In a Randomised Controlled Trial, the preference of a new drug was tested against an established drug by giving both drugs to each of 90 people. Assume that the two drugs are equally preferred, that is, the probability that a patient prefers either of the drugs is equal (50\%). Use one of the binomial functions in R to compute the probability that 60 or more patients would prefer the new drug. In completing this question, determine:

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
  The number of trials (n)
\end{enumerate}

\begin{quote}
Here, each participant represents a `trial', so n is 90.
\end{quote}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  The number of successes we are interested in (k)
\end{enumerate}

\begin{quote}
We are interested in determining the probability that 60 or more participants prefer the new drug, so k is 60.
\end{quote}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  The probability of success for each trial (p)
\end{enumerate}

\begin{quote}
We are told to assume that the two drugs are equally preferred, so p is 0.5.
\end{quote}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{3}
\tightlist
\item
  The form of the R function: dbinom or pbinom
\end{enumerate}

\begin{quote}
We need to calculate the probability that 60 or more participants prefer the new drug. The two R functions can be interpreted as follows:
- the \texttt{dbinom} function gives the probability of observing 60 successes;
- the \texttt{pbinom} function gives the probability of observing 60 or fewer successes;
- the \texttt{pbinom} function with \texttt{lower.tail=FALSE} gives the probability of observing \emph{more than} 60 successes.
\end{quote}

\begin{quote}
We therefore want to use \texttt{pbinom} function with \texttt{lower.tail=FALSE} here.
\end{quote}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{4}
\tightlist
\item
  The final probability.
\end{enumerate}

\begin{quote}
To calculate the probability of obtaining 60 or more successes, we need to calculate the probabibility of observing \emph{more than} 59 successes. So the function we use is:
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{pbinom}\NormalTok{(}\AttributeTok{q=}\DecValTok{59}\NormalTok{, }\AttributeTok{size=}\DecValTok{90}\NormalTok{, }\AttributeTok{prob=}\FloatTok{0.5}\NormalTok{, }\AttributeTok{lower.tail =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.001030133
\end{verbatim}

\begin{quote}
Therefore, the probability that 60 or more patients would prefer the new drug is 0.001 or 0.1\%.
\end{quote}

\hypertarget{activity-2.2}{%
\subsection*{Activity 2.2}\label{activity-2.2}}
\addcontentsline{toc}{subsection}{Activity 2.2}

A case of Schistosomiasis is identified by the detection of schistosome ova in a faecal sample. In patients with a low level of infection, a field technique of faecal examination has a probability of 0.35 of detecting ova in any one faecal sample. If five samples are routinely examined for each patient, use R to compute the probability that a patient with a low level of infection:

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
  Will not be identified?
\end{enumerate}

\begin{quote}
In all of these questions, \texttt{size} is 5 and \texttt{prob} is 0.35. Here we need to calculate the probability of P(X=0), and we can use the \texttt{dbinom} function:
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{dbinom}\NormalTok{(}\AttributeTok{x=}\DecValTok{0}\NormalTok{, }\AttributeTok{size=}\DecValTok{5}\NormalTok{, }\AttributeTok{prob=}\FloatTok{0.35}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1160291
\end{verbatim}

\begin{quote}
The probability P(X=0) = 0.116 or 11.6\%.
\end{quote}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  Will be identified in two of the samples?
\end{enumerate}

\begin{quote}
The probability P(X=2)= 0. 336 or 33.6\%:
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{dbinom}\NormalTok{(}\AttributeTok{x=}\DecValTok{2}\NormalTok{, }\AttributeTok{size=}\DecValTok{5}\NormalTok{, }\AttributeTok{prob=}\FloatTok{0.35}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.3364156
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  Will be identified in all the samples?
\end{enumerate}

The probability P(X=5) = .005 or 0.5\%:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{dbinom}\NormalTok{(}\AttributeTok{x=}\DecValTok{5}\NormalTok{, }\AttributeTok{size=}\DecValTok{5}\NormalTok{, }\AttributeTok{prob=}\FloatTok{0.35}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.005252187
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{3}
\tightlist
\item
  Will be identified in at most 3 of the samples?
\end{enumerate}

\begin{quote}
``At most 3 samples'' is the same as 3 or fewer samples, so we can use the pbinom function. The probability P(X≤3) = .946 or 94.6\%:
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{pbinom}\NormalTok{(}\AttributeTok{q=}\DecValTok{3}\NormalTok{, }\AttributeTok{size=}\DecValTok{5}\NormalTok{, }\AttributeTok{prob=}\FloatTok{0.35}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9459775
\end{verbatim}

\hypertarget{activity-2.3}{%
\subsection*{Activity 2.3}\label{activity-2.3}}
\addcontentsline{toc}{subsection}{Activity 2.3}

If weights of men are Normally distributed with a population mean \(\mu\) = 87, and a population standard deviation, \(\sigma\) = 8 kg:

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
  What is the probability that a man will weigh 95 kg or more? Draw a Normal curve of the area represented by this probability in the population (i.e.~with \(\mu\) = 87 kg and \(\sigma\) = 8 kg).
\end{enumerate}

\begin{quote}
The curve representing the desired probability is drawn below, with the region above 95kg shaded to represent the probability of interest. Note that this curve was generated by a computer: a hand-drawn figure is completely acceptable. A hand-drawn figure will probably look much less tidy, but the main thing to notice is that the shaded area looks like it would represent less than 50\% of the total curve. Therefore, our final probability should be less than 0.5.
\end{quote}

\begin{figure}
\centering
\includegraphics{phcm9795-solutions-R_files/figure-latex/unnamed-chunk-18-1.pdf}
\caption{\label{fig:unnamed-chunk-18}Probability that a man will weigh 95kg or more}
\end{figure}

\begin{quote}
The probability is calculated as:
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Probability:}
\FunctionTok{pnorm}\NormalTok{(}\DecValTok{95}\NormalTok{, }\AttributeTok{mean=}\DecValTok{87}\NormalTok{, }\AttributeTok{sd=}\DecValTok{8}\NormalTok{, }\AttributeTok{lower.tail=}\ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1586553
\end{verbatim}

\begin{quote}
Therefore, the probability that a man from this population weighs 95 kg or more is 0.16 or 16\%.
\end{quote}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  What is the probability that a man will weigh more than 75 kg but less than 95 kg? Draw the area represented by this probability on a standardised Normal curve.
\end{enumerate}

\begin{quote}
The curve to represent this probability is shown below. To obtain the probability represented by the shaded region, we again use the fact that the total area under a Normal curve must add to 1. Let's break the curve into three parts, which we will call A, B and C.
\end{quote}

\includegraphics{phcm9795-solutions-R_files/figure-latex/unnamed-chunk-20-1.pdf}

\begin{quote}
We use that fact that A+B+C=1 to derive that B = 1-- A -- C. We have already calculated C in Part (a) of this question. To calculate A:
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{pnorm}\NormalTok{(}\DecValTok{75}\NormalTok{, }\AttributeTok{mean=}\DecValTok{87}\NormalTok{, }\AttributeTok{sd=}\DecValTok{8}\NormalTok{, }\AttributeTok{lower.tail=}\ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.0668072
\end{verbatim}

P(Weight \textless{} 75) = 0.0668.

\begin{quote}
The region B is calculated as: 1 - 0.1587 - 0.0668 = 0.7745.
\end{quote}

\begin{quote}
So the probability that a man will weigh more than 75 kg but less than 95 kg is 0.77, or 77\%.
\end{quote}

\hypertarget{activity-2.4}{%
\subsection*{Activity 2.4}\label{activity-2.4}}
\addcontentsline{toc}{subsection}{Activity 2.4}

Using the health survey data described in the R notes of this module, create a new variable, BMI, which is equal to a person's weight (in kg) divided by their height (in metres) squared (i.e.~\(\text{BMI} = \frac{\text{weight (kg)}}{\text{[height (m)]}^2}\). Categorise BMI using the WHO categories provided in the R notes. Create a two-way table to display the distribution of BMI categories by sex (sex: 1 = respondent identifies as male; 2 = respondent identifies as female). Does there appear to be a difference in categorised BMI between males and females?

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(readxl)}
\FunctionTok{library}\NormalTok{(jmv)}

\NormalTok{survey }\OtherTok{\textless{}{-}} \FunctionTok{read\_excel}\NormalTok{(}\StringTok{"data/examples/health{-}survey.xlsx"}\NormalTok{)}
\FunctionTok{summary}\NormalTok{(survey)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       sex           height          weight      
##  Min.   :1.00   Min.   :1.220   Min.   : 22.70  
##  1st Qu.:1.00   1st Qu.:1.630   1st Qu.: 68.00  
##  Median :2.00   Median :1.700   Median : 79.40  
##  Mean   :1.55   Mean   :1.698   Mean   : 81.19  
##  3rd Qu.:2.00   3rd Qu.:1.780   3rd Qu.: 90.70  
##  Max.   :2.00   Max.   :2.010   Max.   :213.20
\end{verbatim}

\begin{quote}
After reading in the data, we define sex as a factor, and create BMI:
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{survey}\SpecialCharTok{$}\NormalTok{sex }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(survey}\SpecialCharTok{$}\NormalTok{sex, }\AttributeTok{level=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{), }\AttributeTok{labels=}\FunctionTok{c}\NormalTok{(}\StringTok{"Male"}\NormalTok{, }\StringTok{"Female"}\NormalTok{))}

\NormalTok{survey}\SpecialCharTok{$}\NormalTok{bmi }\OtherTok{=}\NormalTok{ survey}\SpecialCharTok{$}\NormalTok{weight }\SpecialCharTok{/}\NormalTok{ (survey}\SpecialCharTok{$}\NormalTok{height}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{quote}
After creating BMI, we should examine its distribution using a histogram and/or a boxplot:
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{hist}\NormalTok{(survey}\SpecialCharTok{$}\NormalTok{bmi, }\AttributeTok{main=}\StringTok{"Histogram of BMI"}\NormalTok{, }\AttributeTok{xlab=}\StringTok{"Body mass index (kg/m2)"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{phcm9795-solutions-R_files/figure-latex/unnamed-chunk-24-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{boxplot}\NormalTok{(survey}\SpecialCharTok{$}\NormalTok{bmi, }\AttributeTok{main=}\StringTok{"Boxplot of BMI"}\NormalTok{, }\AttributeTok{ylab=}\StringTok{"Body mass index (kg/m2)"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{phcm9795-solutions-R_files/figure-latex/unnamed-chunk-24-2.pdf}

\begin{quote}
The boxplot in particular shows that there are some extreme values of BMI. We can examine these records by viewing records with BMI less than, say 15, or greater than 45:
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{subset}\NormalTok{(survey, bmi}\SpecialCharTok{\textless{}}\DecValTok{15}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 2 x 4
##   sex    height weight   bmi
##   <fct>   <dbl>  <dbl> <dbl>
## 1 Female   1.57   22.7  9.21
## 2 Female   1.65   40.8 15.0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{subset}\NormalTok{(survey, bmi}\SpecialCharTok{\textgreater{}}\DecValTok{45}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 16 x 4
##    sex    height weight   bmi
##    <fct>   <dbl>  <dbl> <dbl>
##  1 Female   1.52  105    45.4
##  2 Male     1.85  174.   50.8
##  3 Female   1.22   74.8  50.3
##  4 Male     1.93  213.   57.2
##  5 Female   1.63  127    47.8
##  6 Female   1.55  115.   48.0
##  7 Female   1.65  131.   48.2
##  8 Female   1.55  109.   45.3
##  9 Male     1.78  143.   45.1
## 10 Female   1.65  127    46.6
## 11 Female   1.63  132.   49.5
## 12 Female   1.7   152    52.6
## 13 Female   1.6   127    49.6
## 14 Female   1.5   106.   47.2
## 15 Female   1.73  154.   51.5
## 16 Female   1.6   116.   45.4
\end{verbatim}

\begin{quote}
The smallest BMI of 9.2 kg/m2 is very low, with a weight of 22.7 kg. We should check the recorded height and weight values against the original data (paper records, survey responses) if they were available. However, as a weight of 22.7kg is not impossible, this record will not be deleted. An alternative approach would be to analyse the data including the very low BMI and again excluding the very low BMI as a sensitivity analysis.
The largest BMI values are based on participants with large weights, and none of these seem biologically implausible. Therefore, no changes will be made to participants with small or large values of BMI.
\end{quote}

\begin{quote}
We can use the \texttt{cut()} function to create the BMI categories. The WHO cutpoints are inclusive of the lower-bound, so we use \texttt{right=FALSE}. After creating the categories, it is good practice to check the resulting categories using \texttt{summary()}:
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{survey}\SpecialCharTok{$}\NormalTok{bmi\_cat }\OtherTok{\textless{}{-}} \FunctionTok{cut}\NormalTok{(survey}\SpecialCharTok{$}\NormalTok{bmi, }\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FloatTok{18.5}\NormalTok{, }\DecValTok{25}\NormalTok{, }\DecValTok{30}\NormalTok{, }\DecValTok{35}\NormalTok{, }\DecValTok{40}\NormalTok{, }\DecValTok{100}\NormalTok{), }\AttributeTok{right=}\ConstantTok{FALSE}\NormalTok{)}
\FunctionTok{summary}\NormalTok{(survey}\SpecialCharTok{$}\NormalTok{bmi\_cat)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [0,18.5) [18.5,25)   [25,30)   [30,35)   [35,40)  [40,100) 
##        18       362       411       201       101        47
\end{verbatim}

\begin{quote}
Finally, we can create a two-way table using the \texttt{contTables()} function within the \texttt{jmv} package. We can define the rows by BMI category, and the columns by sex:
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{contTables}\NormalTok{(}\AttributeTok{data=}\NormalTok{survey,}
           \AttributeTok{rows =}\NormalTok{ bmi\_cat,}
           \AttributeTok{cols =}\NormalTok{ sex)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  CONTINGENCY TABLES
## 
##  Contingency Tables                       
##  ──────────────────────────────────────── 
##    bmi_cat      Male    Female    Total   
##  ──────────────────────────────────────── 
##    [0,18.5)        6        12       18   
##    [18.5,25)     134       228      362   
##    [25,30)       216       195      411   
##    [30,35)        95       106      201   
##    [35,40)        46        55      101   
##    [40,100)       16        31       47   
##    Total         513       627     1140   
##  ──────────────────────────────────────── 
## 
## 
##  χ² Tests                              
##  ───────────────────────────────────── 
##          Value       df    p           
##  ───────────────────────────────────── 
##    χ²    22.49802     5    0.0004209   
##    N         1140                      
##  ─────────────────────────────────────
\end{verbatim}

\begin{quote}
To assess whether there is a difference in BMI between males and females, we should look at the within-sex relative frequencies. In other words, column percents (for this table), by specifying \texttt{pcCol\ =\ TRUE}:
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{contTables}\NormalTok{(}\AttributeTok{data=}\NormalTok{survey,}
           \AttributeTok{rows =}\NormalTok{ bmi\_cat,}
           \AttributeTok{cols =}\NormalTok{ sex,}
           \AttributeTok{pcCol =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  CONTINGENCY TABLES
## 
##  Contingency Tables                                                      
##  ─────────────────────────────────────────────────────────────────────── 
##    bmi_cat                         Male         Female       Total       
##  ─────────────────────────────────────────────────────────────────────── 
##    [0,18.5)     Observed                   6           12           18   
##                 % within column      1.16959      1.91388      1.57895   
##                                                                          
##    [18.5,25)    Observed                 134          228          362   
##                 % within column     26.12086     36.36364     31.75439   
##                                                                          
##    [25,30)      Observed                 216          195          411   
##                 % within column     42.10526     31.10048     36.05263   
##                                                                          
##    [30,35)      Observed                  95          106          201   
##                 % within column     18.51852     16.90590     17.63158   
##                                                                          
##    [35,40)      Observed                  46           55          101   
##                 % within column      8.96686      8.77193      8.85965   
##                                                                          
##    [40,100)     Observed                  16           31           47   
##                 % within column      3.11891      4.94418      4.12281   
##                                                                          
##    Total        Observed                 513          627         1140   
##                 % within column    100.00000    100.00000    100.00000   
##  ─────────────────────────────────────────────────────────────────────── 
## 
## 
##  χ² Tests                              
##  ───────────────────────────────────── 
##          Value       df    p           
##  ───────────────────────────────────── 
##    χ²    22.49802     5    0.0004209   
##    N         1140                      
##  ─────────────────────────────────────
\end{verbatim}

\begin{quote}
From this health survey, it appears that men are more likely to have BMIs indicating Pre-Obesity (men 42\% vs women 31\%) and Obesity Class I (men 19\% vs women 17\%), compared to women who are more likely to have BMIs indicating Normal weight (women 36\% vs men 26\%).
\end{quote}

\hypertarget{activity-2.5}{%
\subsection*{Activity 2.5}\label{activity-2.5}}
\addcontentsline{toc}{subsection}{Activity 2.5}

The data in the file \texttt{Activity\_S2.5.rds} (available on Moodle) has information about birth weight and length of stay collected from 117 babies admitted consecutively to a hospital for surgery. For each variable:

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Create a histogram to inspect the distribution of the variable;
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{babies }\OtherTok{\textless{}{-}} \FunctionTok{readRDS}\NormalTok{(}\StringTok{"data/activities/Activity\_S2.5{-}LengthOfStay.rds"}\NormalTok{)}
\FunctionTok{summary}\NormalTok{(babies)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        ID          Sex        BirthWt        GestAge        LengthStay    
##  Min.   : 25   female:55   Min.   :1500   Min.   :31.00   Min.   :  0.00  
##  1st Qu.: 54   male  :62   1st Qu.:2012   1st Qu.:35.75   1st Qu.: 21.00  
##  Median : 83               Median :2438   Median :36.00   Median : 30.00  
##  Mean   : 83               Mean   :2451   Mean   :36.56   Mean   : 41.08  
##  3rd Qu.:112               3rd Qu.:2830   3rd Qu.:38.00   3rd Qu.: 43.00  
##  Max.   :141               Max.   :3545   Max.   :41.00   Max.   :244.00  
##                            NA's   :1      NA's   :5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{hist}\NormalTok{(babies}\SpecialCharTok{$}\NormalTok{BirthWt, }\AttributeTok{main=}\StringTok{"Histogram of birth weights"}\NormalTok{,}
     \AttributeTok{xlab=}\StringTok{"Birth weight (kg)"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{phcm9795-solutions-R_files/figure-latex/unnamed-chunk-29-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# We can specify our own cutpoints using the breaks command, with the seq() function:}
\FunctionTok{hist}\NormalTok{(babies}\SpecialCharTok{$}\NormalTok{BirthWt, }\AttributeTok{main=}\StringTok{"Histogram of birth weights"}\NormalTok{,}
     \AttributeTok{xlab=}\StringTok{"Birth weight (kg)"}\NormalTok{,}
     \AttributeTok{breaks=}\FunctionTok{seq}\NormalTok{(}\AttributeTok{from=}\DecValTok{1500}\NormalTok{, }\AttributeTok{to=}\DecValTok{4000}\NormalTok{, }\AttributeTok{by=}\DecValTok{250}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{phcm9795-solutions-R_files/figure-latex/unnamed-chunk-29-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{hist}\NormalTok{(babies}\SpecialCharTok{$}\NormalTok{LengthStay, }\AttributeTok{main=}\StringTok{"Histogram of lengths of stay"}\NormalTok{,}
     \AttributeTok{xlab=}\StringTok{"Length of stay (days)"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{phcm9795-solutions-R_files/figure-latex/unnamed-chunk-29-3.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{hist}\NormalTok{(babies}\SpecialCharTok{$}\NormalTok{LengthStay, }\AttributeTok{main=}\StringTok{"Histogram of lengths of stay"}\NormalTok{,}
     \AttributeTok{xlab=}\StringTok{"Length of stay (days)"}\NormalTok{,}
     \AttributeTok{breaks=}\FunctionTok{seq}\NormalTok{(}\AttributeTok{from=}\DecValTok{0}\NormalTok{, }\AttributeTok{to=}\DecValTok{250}\NormalTok{, }\AttributeTok{by=}\DecValTok{25}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{phcm9795-solutions-R_files/figure-latex/unnamed-chunk-29-4.pdf}

\begin{quote}
The histogram for birthweight shows a roughly symmetric distribution. The histogram for length of stay shows a highly skewed distribution (skewed to the right).
\end{quote}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Complete the following summary statistics for each variable:

  \begin{itemize}
  \tightlist
  \item
    mean and median;
  \item
    standard deviation and interquartile range;
  \item
    skewness and kurtosis.
  \end{itemize}
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{descriptives}\NormalTok{(}\AttributeTok{data =}\NormalTok{ babies,}
             \AttributeTok{vars =} \FunctionTok{c}\NormalTok{(BirthWt, LengthStay),}
             \AttributeTok{pc =} \ConstantTok{TRUE}\NormalTok{,}
             \AttributeTok{skew =} \ConstantTok{TRUE}\NormalTok{,}
             \AttributeTok{kurt =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  DESCRIPTIVES
## 
##  Descriptives                                        
##  ─────────────────────────────────────────────────── 
##                           BirthWt       LengthStay   
##  ─────────────────────────────────────────────────── 
##    N                             116           117   
##    Missing                         1             0   
##    Mean                     2451.207      41.07692   
##    Median                   2437.500      30.00000   
##    Standard deviation       504.8221      36.92984   
##    Minimum                  1500.000      0.000000   
##    Maximum                  3545.000      244.0000   
##    Skewness                0.3548827      3.090351   
##    Std. error skewness     0.2245612     0.2236233   
##    Kurtosis               -0.7448547      11.56803   
##    Std. error kurtosis     0.4455276     0.4436951   
##    25th percentile          2012.000      21.00000   
##    50th percentile          2437.500      30.00000   
##    75th percentile          2830.000      43.00000   
##  ───────────────────────────────────────────────────
\end{verbatim}

Make a decision about whether each variable is symmetric or not, and which measure of central tendency and variability should be reported.

\begin{quote}
As birthweight follows a roughly symmetric distribution, we should present the mean and standard deviation as the appropriate measures of central tendency and spread. Notice that the mean and median are similar, which is to be expected for a symmetric distribution.
\end{quote}

\begin{quote}
Length of stay is highly skewed. In this case, the median and interquartile range are the appropriate measures to present. Notice that the mean is higher than the median, which is typical for distributions that are skewed to the right.
\end{quote}

\hypertarget{activity-2.6}{%
\subsection*{Activity 2.6}\label{activity-2.6}}
\addcontentsline{toc}{subsection}{Activity 2.6}

The data set of hospital stay data for 1323 hypothetical patients is available on Moodle in csv format (\texttt{Activity2.6.csv}). Import this dataset into R There are two variables in this dataset:

\begin{itemize}
\tightlist
\item
  female: female=1; male=0
\item
  los: length of stay in days
\end{itemize}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
  Use R to examine the distribution of length of stay: overall; and separately for females and males. Comment on the distributions.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{hospstay }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"data/activities/Activity\_S2.5.csv"}\NormalTok{)}

\FunctionTok{summary}\NormalTok{(hospstay)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      female            los        
##  Min.   :0.0000   Min.   :  0.00  
##  1st Qu.:0.0000   1st Qu.:  4.00  
##  Median :0.0000   Median :  9.00  
##  Mean   :0.1104   Mean   : 12.52  
##  3rd Qu.:0.0000   3rd Qu.: 17.00  
##  Max.   :1.0000   Max.   :106.00
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Define female as a factor}
\NormalTok{hospstay}\SpecialCharTok{$}\NormalTok{female }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(hospstay}\SpecialCharTok{$}\NormalTok{female, }\AttributeTok{levels=}\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{1}\NormalTok{), }\AttributeTok{labels=}\FunctionTok{c}\NormalTok{(}\StringTok{"Male"}\NormalTok{, }\StringTok{"Female"}\NormalTok{))}
\FunctionTok{summary}\NormalTok{(hospstay}\SpecialCharTok{$}\NormalTok{female)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Male Female 
##   1177    146
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{hist}\NormalTok{(hospstay}\SpecialCharTok{$}\NormalTok{los, }\AttributeTok{main=}\StringTok{"Histogram of hospital stay"}\NormalTok{, }\AttributeTok{xlab=}\StringTok{"Length of stay (days)"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{phcm9795-solutions-R_files/figure-latex/unnamed-chunk-31-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{boxplot}\NormalTok{(hospstay}\SpecialCharTok{$}\NormalTok{los, }\AttributeTok{main=}\StringTok{"Boxplot of hospital stay"}\NormalTok{, }\AttributeTok{ylab=}\StringTok{"Length of stay (days)"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{phcm9795-solutions-R_files/figure-latex/unnamed-chunk-31-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{hospstay\_males }\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(hospstay, female}\SpecialCharTok{==}\StringTok{"Male"}\NormalTok{)}
\NormalTok{hospstay\_females }\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(hospstay, female}\SpecialCharTok{==}\StringTok{"Female"}\NormalTok{)}

\CommentTok{\# Set the graphics parameters to plot 2 rows and 2 columns:}
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{))}

\CommentTok{\# Specify each plot separately}
\FunctionTok{hist}\NormalTok{(hospstay\_males}\SpecialCharTok{$}\NormalTok{los, }\AttributeTok{xlab=}\StringTok{"Length of stay (days)"}\NormalTok{, }\AttributeTok{main=}\StringTok{"Males"}\NormalTok{)}
\FunctionTok{hist}\NormalTok{(hospstay\_females}\SpecialCharTok{$}\NormalTok{los, }\AttributeTok{xlab=}\StringTok{"Length of stay (days)"}\NormalTok{, }\AttributeTok{main=}\StringTok{"Females"}\NormalTok{)}

\FunctionTok{boxplot}\NormalTok{(hospstay\_males}\SpecialCharTok{$}\NormalTok{los, }\AttributeTok{ylab=}\StringTok{"Length of stay (days)"}\NormalTok{, }\AttributeTok{main=}\StringTok{"Males"}\NormalTok{)}
\FunctionTok{boxplot}\NormalTok{(hospstay\_females}\SpecialCharTok{$}\NormalTok{los, }\AttributeTok{ylab=}\StringTok{"Length of stay (days)"}\NormalTok{, }\AttributeTok{main=}\StringTok{"Females"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{phcm9795-solutions-R_files/figure-latex/unnamed-chunk-31-3.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Reset graphics parameters}
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{quote}
The histograms for overall length of stay and length of stay by gender all show that length of stay is heavily skewed (skewed to the right).
\end{quote}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  Use R to calculate measures of central tendency for hospital stay to obtain information about the average duration of hospital stay. Which summary statistics should you report and why? Report the appropriate statistics of the spread and measure of central tendency chosen.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{descriptives}\NormalTok{(}\AttributeTok{data =}\NormalTok{ hospstay,}
             \AttributeTok{vars =}\NormalTok{ los,}
             \AttributeTok{pc =} \ConstantTok{TRUE}\NormalTok{,}
             \AttributeTok{skew =} \ConstantTok{TRUE}\NormalTok{,}
             \AttributeTok{kurt =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  DESCRIPTIVES
## 
##  Descriptives                          
##  ───────────────────────────────────── 
##                           los          
##  ───────────────────────────────────── 
##    N                            1323   
##    Missing                         0   
##    Mean                     12.51550   
##    Median                          9   
##    Standard deviation       12.59933   
##    Minimum                         0   
##    Maximum                       106   
##    Skewness                 1.947803   
##    Std. error skewness    0.06726732   
##    Kurtosis                 5.166837   
##    Std. error kurtosis     0.1344336   
##    25th percentile          4.000000   
##    50th percentile          9.000000   
##    75th percentile          17.00000   
##  ─────────────────────────────────────
\end{verbatim}

\begin{quote}
As the distribution of length of stay is highly skewed, the median and interquartile range should be presented. These can be calculated in the usual way, using the \texttt{descriptives()} function. The median length of stay is 9 days, with an interquartile range of 4 to 17 days.
\end{quote}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  Calculate the measures of central tendency for hospital duration separately for males and females. What can you conclude from comparing these measures for males and females?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{descriptives}\NormalTok{(}\AttributeTok{data =}\NormalTok{ hospstay,}
             \AttributeTok{vars =}\NormalTok{ los,}
             \AttributeTok{splitBy =}\NormalTok{ female,}
             \AttributeTok{pc =} \ConstantTok{TRUE}\NormalTok{,}
             \AttributeTok{skew =} \ConstantTok{TRUE}\NormalTok{,}
             \AttributeTok{kurt =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  DESCRIPTIVES
## 
##  Descriptives                                    
##  ─────────────────────────────────────────────── 
##                           female    los          
##  ─────────────────────────────────────────────── 
##    N                      Male            1177   
##                           Female           146   
##    Missing                Male               0   
##                           Female             0   
##    Mean                   Male        12.75531   
##                           Female      10.58219   
##    Median                 Male               9   
##                           Female      7.500000   
##    Standard deviation     Male        12.83475   
##                           Female      10.34625   
##    Minimum                Male               0   
##                           Female             0   
##    Maximum                Male             106   
##                           Female            53   
##    Skewness               Male        1.943967   
##                           Female      1.697009   
##    Std. error skewness    Male      0.07130745   
##                           Female     0.2006795   
##    Kurtosis               Male        5.128450   
##                           Female      3.067601   
##    Std. error kurtosis    Male       0.1424946   
##                           Female     0.3987670   
##    25th percentile        Male        4.000000   
##                           Female      3.000000   
##    50th percentile        Male        9.000000   
##                           Female      7.500000   
##    75th percentile        Male        18.00000   
##                           Female      14.00000   
##  ───────────────────────────────────────────────
\end{verbatim}

\begin{quote}
Lengths of stay are similar for men (median: 9 days, interquartile range: 4 to 18 days) and women (median: 8 days, interquartile range: 3 to 14 days).
\end{quote}

\hypertarget{module-2-full-script}{%
\chapter*{Module 2: Full script}\label{module-2-full-script}}
\addcontentsline{toc}{chapter}{Module 2: Full script}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Author: Timothy Dobbins}
\CommentTok{\# Date: May, 2022}
\CommentTok{\# Purpose: Learning activities for Module 2}

\FunctionTok{library}\NormalTok{(jmv)}
\FunctionTok{library}\NormalTok{(readxl)}

\DocumentationTok{\#\#\# Activity 2.1}

\FunctionTok{pbinom}\NormalTok{(}\AttributeTok{q=}\DecValTok{59}\NormalTok{, }\AttributeTok{size=}\DecValTok{90}\NormalTok{, }\AttributeTok{prob=}\FloatTok{0.5}\NormalTok{, }\AttributeTok{lower.tail =} \ConstantTok{FALSE}\NormalTok{)}


\DocumentationTok{\#\#\# Activity 2.2}

\FunctionTok{dbinom}\NormalTok{(}\AttributeTok{x=}\DecValTok{0}\NormalTok{, }\AttributeTok{size=}\DecValTok{5}\NormalTok{, }\AttributeTok{prob=}\FloatTok{0.35}\NormalTok{)}
\FunctionTok{dbinom}\NormalTok{(}\AttributeTok{x=}\DecValTok{2}\NormalTok{, }\AttributeTok{size=}\DecValTok{5}\NormalTok{, }\AttributeTok{prob=}\FloatTok{0.35}\NormalTok{)}
\FunctionTok{dbinom}\NormalTok{(}\AttributeTok{x=}\DecValTok{5}\NormalTok{, }\AttributeTok{size=}\DecValTok{5}\NormalTok{, }\AttributeTok{prob=}\FloatTok{0.35}\NormalTok{)}
\FunctionTok{pbinom}\NormalTok{(}\AttributeTok{q=}\DecValTok{3}\NormalTok{, }\AttributeTok{size=}\DecValTok{5}\NormalTok{, }\AttributeTok{prob=}\FloatTok{0.35}\NormalTok{)}


\DocumentationTok{\#\#\# Activity 2.3}
\NormalTok{A }\OtherTok{\textless{}{-}} \FunctionTok{pnorm}\NormalTok{(}\DecValTok{75}\NormalTok{, }\AttributeTok{mean=}\DecValTok{87}\NormalTok{, }\AttributeTok{sd=}\DecValTok{8}\NormalTok{, }\AttributeTok{lower.tail=}\ConstantTok{TRUE}\NormalTok{)}
\NormalTok{A}

\NormalTok{C }\OtherTok{\textless{}{-}} \FunctionTok{pnorm}\NormalTok{(}\DecValTok{95}\NormalTok{, }\AttributeTok{mean=}\DecValTok{87}\NormalTok{, }\AttributeTok{sd=}\DecValTok{8}\NormalTok{, }\AttributeTok{lower.tail=}\ConstantTok{FALSE}\NormalTok{)   }
\NormalTok{C}

\NormalTok{B }\OtherTok{\textless{}{-}} \DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ A }\SpecialCharTok{{-}}\NormalTok{ C}
\NormalTok{B}


\DocumentationTok{\#\#\# Activity 2.4}

\NormalTok{survey }\OtherTok{\textless{}{-}} \FunctionTok{read\_excel}\NormalTok{(}\StringTok{"data/examples/health{-}survey.xlsx"}\NormalTok{)}
\FunctionTok{summary}\NormalTok{(survey)}

\NormalTok{survey}\SpecialCharTok{$}\NormalTok{sex }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(survey}\SpecialCharTok{$}\NormalTok{sex, }\AttributeTok{level=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{), }\AttributeTok{labels=}\FunctionTok{c}\NormalTok{(}\StringTok{"Male"}\NormalTok{, }\StringTok{"Female"}\NormalTok{))}

\NormalTok{survey}\SpecialCharTok{$}\NormalTok{bmi }\OtherTok{=}\NormalTok{ survey}\SpecialCharTok{$}\NormalTok{weight }\SpecialCharTok{/}\NormalTok{ (survey}\SpecialCharTok{$}\NormalTok{height}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\FunctionTok{hist}\NormalTok{(survey}\SpecialCharTok{$}\NormalTok{bmi, }\AttributeTok{main=}\StringTok{"Histogram of BMI"}\NormalTok{, }\AttributeTok{xlab=}\StringTok{"BMI (kg/m2)"}\NormalTok{)}
\FunctionTok{boxplot}\NormalTok{(survey}\SpecialCharTok{$}\NormalTok{bmi, }\AttributeTok{main=}\StringTok{"Boxplot of BMI"}\NormalTok{, }\AttributeTok{ylab=}\StringTok{"BMI (kg/m2)"}\NormalTok{)}

\FunctionTok{subset}\NormalTok{(survey, bmi}\SpecialCharTok{\textless{}}\DecValTok{15}\NormalTok{)}
\FunctionTok{subset}\NormalTok{(survey, bmi}\SpecialCharTok{\textgreater{}}\DecValTok{45}\NormalTok{)}

\NormalTok{survey}\SpecialCharTok{$}\NormalTok{bmi\_cat }\OtherTok{\textless{}{-}} \FunctionTok{cut}\NormalTok{(survey}\SpecialCharTok{$}\NormalTok{bmi, }\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FloatTok{18.5}\NormalTok{, }\DecValTok{25}\NormalTok{, }\DecValTok{30}\NormalTok{, }\DecValTok{35}\NormalTok{, }\DecValTok{40}\NormalTok{, }\DecValTok{100}\NormalTok{), }\AttributeTok{right=}\ConstantTok{FALSE}\NormalTok{)}
\FunctionTok{summary}\NormalTok{(survey}\SpecialCharTok{$}\NormalTok{bmi\_cat)}

\FunctionTok{contTables}\NormalTok{(}\AttributeTok{data=}\NormalTok{survey,}
           \AttributeTok{rows =}\NormalTok{ bmi\_cat,}
           \AttributeTok{cols =}\NormalTok{ sex)}

\FunctionTok{contTables}\NormalTok{(}\AttributeTok{data=}\NormalTok{survey,}
           \AttributeTok{rows =}\NormalTok{ bmi\_cat,}
           \AttributeTok{cols =}\NormalTok{ sex,}
           \AttributeTok{pcCol =} \ConstantTok{TRUE}\NormalTok{)}

\DocumentationTok{\#\#\# Activity 2.5}
\NormalTok{babies }\OtherTok{\textless{}{-}} \FunctionTok{readRDS}\NormalTok{(}\StringTok{"data/activities/Activity\_S2.5{-}LengthOfStay.rds"}\NormalTok{)}
\FunctionTok{summary}\NormalTok{(babies)}

\FunctionTok{hist}\NormalTok{(babies}\SpecialCharTok{$}\NormalTok{BirthWt, }\AttributeTok{main=}\StringTok{"Histogram of birth weights"}\NormalTok{,}
     \AttributeTok{xlab=}\StringTok{"Birth weight (kg)"}\NormalTok{)}

\CommentTok{\# We can specify our own cutpoints using the breaks command, with the seq() function:}
\FunctionTok{hist}\NormalTok{(babies}\SpecialCharTok{$}\NormalTok{BirthWt, }\AttributeTok{main=}\StringTok{"Histogram of birth weights"}\NormalTok{,}
     \AttributeTok{xlab=}\StringTok{"Birth weight (kg)"}\NormalTok{,}
     \AttributeTok{breaks=}\FunctionTok{seq}\NormalTok{(}\AttributeTok{from=}\DecValTok{1500}\NormalTok{, }\AttributeTok{to=}\DecValTok{4000}\NormalTok{, }\AttributeTok{by=}\DecValTok{250}\NormalTok{))}

\FunctionTok{hist}\NormalTok{(babies}\SpecialCharTok{$}\NormalTok{LengthStay, }\AttributeTok{main=}\StringTok{"Histogram of lengths of stay"}\NormalTok{,}
     \AttributeTok{xlab=}\StringTok{"Length of stay (days)"}\NormalTok{)}

\FunctionTok{hist}\NormalTok{(babies}\SpecialCharTok{$}\NormalTok{LengthStay, }\AttributeTok{main=}\StringTok{"Histogram of lengths of stay"}\NormalTok{,}
     \AttributeTok{xlab=}\StringTok{"Length of stay (days)"}\NormalTok{,}
     \AttributeTok{breaks=}\FunctionTok{seq}\NormalTok{(}\AttributeTok{from=}\DecValTok{0}\NormalTok{, }\AttributeTok{to=}\DecValTok{250}\NormalTok{, }\AttributeTok{by=}\DecValTok{25}\NormalTok{))}

\FunctionTok{descriptives}\NormalTok{(}\AttributeTok{data =}\NormalTok{ babies,}
             \AttributeTok{vars =} \FunctionTok{c}\NormalTok{(BirthWt, LengthStay),}
             \AttributeTok{pc =} \ConstantTok{TRUE}\NormalTok{,}
             \AttributeTok{skew =} \ConstantTok{TRUE}\NormalTok{,}
             \AttributeTok{kurt =} \ConstantTok{TRUE}\NormalTok{)}

\NormalTok{hospstay }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"data/activities/Activity\_S2.5.csv"}\NormalTok{)}

\FunctionTok{summary}\NormalTok{(hospstay)}

\CommentTok{\# Define female as a factor}
\NormalTok{hospstay}\SpecialCharTok{$}\NormalTok{female }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(hospstay}\SpecialCharTok{$}\NormalTok{female, }\AttributeTok{levels=}\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{1}\NormalTok{), }\AttributeTok{labels=}\FunctionTok{c}\NormalTok{(}\StringTok{"Male"}\NormalTok{, }\StringTok{"Female"}\NormalTok{))}
\FunctionTok{summary}\NormalTok{(hospstay}\SpecialCharTok{$}\NormalTok{female)}

\FunctionTok{hist}\NormalTok{(hospstay}\SpecialCharTok{$}\NormalTok{los, }\AttributeTok{main=}\StringTok{"Histogram of hospital stay"}\NormalTok{, }\AttributeTok{xlab=}\StringTok{"Length of stay (days)"}\NormalTok{)}
\FunctionTok{boxplot}\NormalTok{(hospstay}\SpecialCharTok{$}\NormalTok{los, }\AttributeTok{main=}\StringTok{"Boxplot of hospital stay"}\NormalTok{, }\AttributeTok{ylab=}\StringTok{"Length of stay (days)"}\NormalTok{)}

\NormalTok{hospstay\_males }\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(hospstay, female}\SpecialCharTok{==}\StringTok{"Male"}\NormalTok{)}
\NormalTok{hospstay\_females }\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(hospstay, female}\SpecialCharTok{==}\StringTok{"Female"}\NormalTok{)}

\CommentTok{\# Set the graphics parameters to plot 2 rows and 2 columns:}
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{))}

\CommentTok{\# Specify each plot separately}
\FunctionTok{hist}\NormalTok{(hospstay\_males}\SpecialCharTok{$}\NormalTok{los, }\AttributeTok{xlab=}\StringTok{"Length of stay (days)"}\NormalTok{, }\AttributeTok{main=}\StringTok{"Males"}\NormalTok{)}
\FunctionTok{hist}\NormalTok{(hospstay\_females}\SpecialCharTok{$}\NormalTok{los, }\AttributeTok{xlab=}\StringTok{"Length of stay (days)"}\NormalTok{, }\AttributeTok{main=}\StringTok{"Females"}\NormalTok{)}

\FunctionTok{boxplot}\NormalTok{(hospstay\_males}\SpecialCharTok{$}\NormalTok{los, }\AttributeTok{ylab=}\StringTok{"Length of stay (days)"}\NormalTok{, }\AttributeTok{main=}\StringTok{"Males"}\NormalTok{)}
\FunctionTok{boxplot}\NormalTok{(hospstay\_females}\SpecialCharTok{$}\NormalTok{los, }\AttributeTok{ylab=}\StringTok{"Length of stay (days)"}\NormalTok{, }\AttributeTok{main=}\StringTok{"Females"}\NormalTok{)}

\CommentTok{\# Reset graphics parameters}
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{))}

\FunctionTok{descriptives}\NormalTok{(}\AttributeTok{data =}\NormalTok{ hospstay,}
             \AttributeTok{vars =}\NormalTok{ los,}
             \AttributeTok{pc =} \ConstantTok{TRUE}\NormalTok{,}
             \AttributeTok{skew =} \ConstantTok{TRUE}\NormalTok{,}
             \AttributeTok{kurt =} \ConstantTok{TRUE}\NormalTok{)}

\FunctionTok{descriptives}\NormalTok{(}\AttributeTok{data =}\NormalTok{ hospstay,}
             \AttributeTok{vars =}\NormalTok{ los,}
             \AttributeTok{splitBy =}\NormalTok{ female,}
             \AttributeTok{pc =} \ConstantTok{TRUE}\NormalTok{,}
             \AttributeTok{skew =} \ConstantTok{TRUE}\NormalTok{,}
             \AttributeTok{kurt =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{module-3-solutions-to-learning-activities}{%
\chapter*{Module 3: Solutions to Learning Activities}\label{module-3-solutions-to-learning-activities}}
\addcontentsline{toc}{chapter}{Module 3: Solutions to Learning Activities}

\hypertarget{activity-3.1}{%
\subsection*{Activity 3.1}\label{activity-3.1}}
\addcontentsline{toc}{subsection}{Activity 3.1}

An investigator wishes to study people living with agoraphobia (fear of open spaces). The investigator places an advertisement in a newspaper asking for volunteer participants. A total of 100 replies are received of which the investigator randomly selects 30. However, only 15 volunteers turn up for their interview.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Which of the following statements is true?

  \begin{enumerate}
  \def\labelenumii{\alph{enumii})}
  \tightlist
  \item
    The final 15 participants are likely to be a representative sample of the population available to the investigator
  \item
    The final 15 participants are likely to be a representative sample of the population of people with agoraphobia
  \item
    The randomly selected 30 participants are likely to be a representative sample of people with agoraphobia who replied to the newspaper advertisement
  \item
    None of the above
  \end{enumerate}
\end{enumerate}

\begin{quote}
ANSWER: C
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  The basic problem confronted by the investigator is that:

  \begin{enumerate}
  \def\labelenumii{\alph{enumii})}
  \tightlist
  \item
    The accessible population might be different from the target population
  \item
    The sample has been chosen using an unethical method
  \item
    The sample size was too small
  \item
    It is difficult to obtain a sample of people with agoraphobia in a scientific way
  \end{enumerate}
\end{enumerate}

\begin{quote}
ANSWER: A
\end{quote}

\hypertarget{activity-3.2}{%
\subsection*{Activity 3.2}\label{activity-3.2}}
\addcontentsline{toc}{subsection}{Activity 3.2}

A dental epidemiologist wishes to estimate the mean weekly consumption of sweets among children of a given age in her area. After devising a method which enables her to determine the weekly consumption of sweets by a child, she conducted a pilot survey and found that the standard deviation of sweet consumption by the children per week is 85 gm (assuming this is the σ). She considers taking a random sample for the main survey of:

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\tightlist
\item
  25 children, or
\item
  100 children, or
\item
  625 children or
\item
  3,000 children.
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
  Estimate the standard error and maximum likely (95\% confidence) error of the sample mean for each of these four sample sizes.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# i: n=25}
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{25}
\NormalTok{se }\OtherTok{\textless{}{-}} \DecValTok{85} \SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(n)}
\NormalTok{se}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 17
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mle }\OtherTok{\textless{}{-}} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ se}
\NormalTok{mle}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 33.32
\end{verbatim}

\begin{quote}
\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\tightlist
\item
  The standard error of the mean for a sample of 25 = 85/√25 = 17 gm, and the maximum likely error = 1.96 × 17 = 33.32 gm.
\end{enumerate}
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ii: n=100}
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{100}
\NormalTok{se }\OtherTok{\textless{}{-}} \DecValTok{85} \SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(n)}
\NormalTok{se}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 8.5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mle }\OtherTok{\textless{}{-}} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ se}
\NormalTok{mle}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 16.66
\end{verbatim}

\begin{quote}
\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  The standard error of the mean for a sample of 100 = 85/√100 = 8.5 gm, and the maximum likely error =1.96 × 8.5 = 16.66 gm.
\end{enumerate}
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# iii: n=625}
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{625}
\NormalTok{se }\OtherTok{\textless{}{-}} \DecValTok{85} \SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(n)}
\NormalTok{se}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3.4
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mle }\OtherTok{\textless{}{-}} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ se}
\NormalTok{mle}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 6.664
\end{verbatim}

\begin{quote}
\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  The standard error of the mean for a sample of 625 = 85/√625 = 3.4 gm, and the maximum likely error =1.96 × 3.4 = 6.66 gm.
\end{enumerate}
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# iv: n=3000}
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{3000}
\NormalTok{se }\OtherTok{\textless{}{-}} \DecValTok{85} \SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(n)}
\NormalTok{se}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.551881
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mle }\OtherTok{\textless{}{-}} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ se}
\NormalTok{mle}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3.041686
\end{verbatim}

\begin{quote}
\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\setcounter{enumi}{3}
\tightlist
\item
  The standard error of the mean for a sample of 3,000 = 85/√3000 = 1.55 gm, and the maximum likely error =1.96 × 1.551881 = 3.04 gm.
\end{enumerate}
\end{quote}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  What happens to the standard error as the sample size increases? What can you say about the precision of the sample mean as the sample size increases?
\end{enumerate}

\begin{quote}
When the sample size increases, the standard error of the mean (and hence the maximum likely error) decreases. Thus, sample means from larger samples are more precise than from smaller samples.
\end{quote}

\hypertarget{activity-3.3}{%
\subsection*{Activity 3.3}\label{activity-3.3}}
\addcontentsline{toc}{subsection}{Activity 3.3}

The dataset for this activity is the same as the one used in Activity 1.4 in Module 1. The file is Activity1.4.rds on Moodle.

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
  Plot a histogram of diastolic BP and describe the distribution.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(jmv)}

\NormalTok{dbp }\OtherTok{\textless{}{-}} \FunctionTok{readRDS}\NormalTok{(}\StringTok{"data/activities/Activity\_S1.4.rds"}\NormalTok{)}

\FunctionTok{hist}\NormalTok{(dbp}\SpecialCharTok{$}\NormalTok{diabp, }
     \AttributeTok{main=}\StringTok{"Figure 3.1: Distribution of diastolic blood pressure"}\NormalTok{, }
     \AttributeTok{xlab=}\StringTok{"Diastolic blood pressure (mmHg)"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{phcm9795-solutions-R_files/figure-latex/unnamed-chunk-39-1.pdf}

\begin{quote}
The distribution is approximately symmetrical, centered about the mean.
\end{quote}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  Use R to obtain an estimate of the mean, standard error of the mean and the 95\% confidence interval for the mean diastolic blood pressure.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{descriptives}\NormalTok{(}\AttributeTok{data=}\NormalTok{dbp, }\AttributeTok{vars=}\NormalTok{diabp, }\AttributeTok{se=}\ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  DESCRIPTIVES
## 
##  Descriptives                       
##  ────────────────────────────────── 
##                          diabp      
##  ────────────────────────────────── 
##    N                          100   
##    Missing                      0   
##    Mean                  82.23000   
##    Std. error mean       1.301522   
##    Median                83.00000   
##    Standard deviation    13.01522   
##    Minimum               56.00000   
##    Maximum               118.0000   
##  ──────────────────────────────────
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t.test}\NormalTok{(dbp}\SpecialCharTok{$}\NormalTok{diabp)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  One Sample t-test
## 
## data:  dbp$diabp
## t = 63.18, df = 99, p-value < 2.2e-16
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  79.6475 84.8125
## sample estimates:
## mean of x 
##     82.23
\end{verbatim}

\begin{quote}
The sample mean is estimated as 82.2 mmHg, and the standard error (SE) of the mean is 1.30 mmHg. The 95\% confidence interval is from 79.6 to 84.8 mmHg.
\end{quote}

\begin{quote}
\emph{Note that the original data have one decimal place. While we could present the mean to two decimal places when reporting the mean, it seems a bit excessive to present a mean blood pressure to two decimal places. Thus we report the mean and 95\% confidence interval for the mean with 1 decimal place.}
\end{quote}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  What can you say about the population mean from these results? (Include in you answer what is meant by the confidence interval of a mean).
\end{enumerate}

\begin{quote}
We are 95\% confident that true mean of the population from which we sampled lies between 79.6 mmHg and 84.8 mmHg.
\end{quote}

\hypertarget{activity-3.4}{%
\subsection*{Activity 3.4}\label{activity-3.4}}
\addcontentsline{toc}{subsection}{Activity 3.4}

Suppose that a random sample of 81 newborn babies delivered in a hospital located in a poor neighbourhood during the last year had a mean birth weight of 2.7 kg and a standard deviation of 0.9 kg. Calculate the 95\% confidence interval for the unknown population mean. Interpret the 95\% confidence interval.

\begin{quote}
This question asks for a confidence interval to be calculated from summarised data. R does not have an in-built function to do this, but we can use the code presented in the R notes to complete this activitiy.
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ci\_mean }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(n, mean, sd, }\AttributeTok{width=}\FloatTok{0.95}\NormalTok{, }\AttributeTok{digits=}\DecValTok{3}\NormalTok{)\{}
\NormalTok{  lcl }\OtherTok{\textless{}{-}}\NormalTok{ mean }\SpecialCharTok{{-}} \FunctionTok{qt}\NormalTok{(}\AttributeTok{p=}\NormalTok{(}\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{width)}\SpecialCharTok{/}\DecValTok{2}\NormalTok{), }\AttributeTok{df=}\NormalTok{n}\DecValTok{{-}1}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ sd}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(n)}
\NormalTok{  ucl }\OtherTok{\textless{}{-}}\NormalTok{ mean }\SpecialCharTok{+} \FunctionTok{qt}\NormalTok{(}\AttributeTok{p=}\NormalTok{(}\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{width)}\SpecialCharTok{/}\DecValTok{2}\NormalTok{), }\AttributeTok{df=}\NormalTok{n}\DecValTok{{-}1}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ sd}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(n)}
  
  \FunctionTok{print}\NormalTok{(}\FunctionTok{paste0}\NormalTok{(width}\SpecialCharTok{*}\DecValTok{100}\NormalTok{, }\StringTok{"\%"}\NormalTok{, }\StringTok{" CI: "}\NormalTok{, }
               \FunctionTok{format}\NormalTok{(}\FunctionTok{round}\NormalTok{(lcl, }\AttributeTok{digits=}\NormalTok{digits), }\AttributeTok{nsmall =}\NormalTok{ digits),}
               \StringTok{" to "}\NormalTok{, }\FunctionTok{format}\NormalTok{(}\FunctionTok{round}\NormalTok{(ucl, }\AttributeTok{digits=}\NormalTok{digits), }\AttributeTok{nsmall =}\NormalTok{ digits) ))}

\NormalTok{\}}

\FunctionTok{ci\_mean}\NormalTok{(}\AttributeTok{n=}\DecValTok{81}\NormalTok{, }\AttributeTok{mean=}\FloatTok{2.7}\NormalTok{, }\AttributeTok{sd=}\FloatTok{0.9}\NormalTok{, }\AttributeTok{width=}\FloatTok{0.95}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "95% CI: 2.501 to 2.899"
\end{verbatim}

\begin{quote}
We are 95\% confident that the true mean birthweight in the hospital located in a poor neighbourhood lies between 2.5 kg and 2.9 kg.
\end{quote}

\hypertarget{module-3-full-script}{%
\chapter*{Module 3: Full script}\label{module-3-full-script}}
\addcontentsline{toc}{chapter}{Module 3: Full script}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Author: Timothy Dobbins}
\CommentTok{\# Date: June, 2022}
\CommentTok{\# Purpose: Learning activities for Module 3}

\FunctionTok{library}\NormalTok{(jmv)}

\CommentTok{\# Activity 3.2}
\CommentTok{\# i: n=25}
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{25}
\NormalTok{se }\OtherTok{\textless{}{-}} \DecValTok{85} \SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(n)}
\NormalTok{se}

\NormalTok{mle }\OtherTok{\textless{}{-}} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ se}
\NormalTok{mle}

\CommentTok{\# ii: n=100}
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{100}
\NormalTok{se }\OtherTok{\textless{}{-}} \DecValTok{85} \SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(n)}
\NormalTok{se}

\NormalTok{mle }\OtherTok{\textless{}{-}} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ se}
\NormalTok{mle}

\CommentTok{\# iii: n=625}
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{625}
\NormalTok{se }\OtherTok{\textless{}{-}} \DecValTok{85} \SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(n)}
\NormalTok{se}

\NormalTok{mle }\OtherTok{\textless{}{-}} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ se}
\NormalTok{mle}

\CommentTok{\# iv: n=3000}
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{3000}
\NormalTok{se }\OtherTok{\textless{}{-}} \DecValTok{85} \SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(n)}
\NormalTok{se}

\NormalTok{mle }\OtherTok{\textless{}{-}} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ se}
\NormalTok{mle}


\CommentTok{\# Activity 3.3}
\NormalTok{dbp }\OtherTok{\textless{}{-}} \FunctionTok{readRDS}\NormalTok{(}\StringTok{"data/activities/Activity\_S1.4.rds"}\NormalTok{)}

\FunctionTok{hist}\NormalTok{(dbp}\SpecialCharTok{$}\NormalTok{diabp, }
     \AttributeTok{main=}\StringTok{"Figure 3.1: Distribution of diastolic blood pressure"}\NormalTok{, }
     \AttributeTok{xlab=}\StringTok{"Diastolic blood pressure (mmHg)"}\NormalTok{)}

\FunctionTok{descriptives}\NormalTok{(}\AttributeTok{data=}\NormalTok{dbp, }\AttributeTok{vars=}\NormalTok{diabp, }\AttributeTok{se=}\ConstantTok{TRUE}\NormalTok{)}
\FunctionTok{t.test}\NormalTok{(dbp}\SpecialCharTok{$}\NormalTok{diabp)}

\CommentTok{\# Activity 3.4}
\NormalTok{ci\_mean }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(n, mean, sd, }\AttributeTok{width=}\FloatTok{0.95}\NormalTok{, }\AttributeTok{digits=}\DecValTok{3}\NormalTok{)\{}
\NormalTok{  lcl }\OtherTok{\textless{}{-}}\NormalTok{ mean }\SpecialCharTok{{-}} \FunctionTok{qt}\NormalTok{(}\AttributeTok{p=}\NormalTok{(}\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{width)}\SpecialCharTok{/}\DecValTok{2}\NormalTok{), }\AttributeTok{df=}\NormalTok{n}\DecValTok{{-}1}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ sd}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(n)}
\NormalTok{  ucl }\OtherTok{\textless{}{-}}\NormalTok{ mean }\SpecialCharTok{+} \FunctionTok{qt}\NormalTok{(}\AttributeTok{p=}\NormalTok{(}\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{width)}\SpecialCharTok{/}\DecValTok{2}\NormalTok{), }\AttributeTok{df=}\NormalTok{n}\DecValTok{{-}1}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ sd}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(n)}
  
  \FunctionTok{print}\NormalTok{(}\FunctionTok{paste0}\NormalTok{(width}\SpecialCharTok{*}\DecValTok{100}\NormalTok{, }\StringTok{"\%"}\NormalTok{, }\StringTok{" CI: "}\NormalTok{, }
               \FunctionTok{format}\NormalTok{(}\FunctionTok{round}\NormalTok{(lcl, }\AttributeTok{digits=}\NormalTok{digits), }\AttributeTok{nsmall =}\NormalTok{ digits),}
               \StringTok{" to "}\NormalTok{, }\FunctionTok{format}\NormalTok{(}\FunctionTok{round}\NormalTok{(ucl, }\AttributeTok{digits=}\NormalTok{digits), }\AttributeTok{nsmall =}\NormalTok{ digits) ))}

\NormalTok{\}}

\FunctionTok{ci\_mean}\NormalTok{(}\AttributeTok{n=}\DecValTok{81}\NormalTok{, }\AttributeTok{mean=}\FloatTok{2.7}\NormalTok{, }\AttributeTok{sd=}\FloatTok{0.9}\NormalTok{, }\AttributeTok{width=}\FloatTok{0.95}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{module-4-solutions-to-learning-activities}{%
\chapter*{Module 4: Solutions to Learning Activities}\label{module-4-solutions-to-learning-activities}}
\addcontentsline{toc}{chapter}{Module 4: Solutions to Learning Activities}

\hypertarget{activity-4.1}{%
\subsection*{Activity 4.1}\label{activity-4.1}}
\addcontentsline{toc}{subsection}{Activity 4.1}

In each of the following situations, what decision should be made about the null hypothesis if the researcher indicates that:

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
  P \textless{} 0.01
\end{enumerate}

\begin{quote}
There is strong evidence against the null hypothesis.
\end{quote}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  P \textgreater{} 0.05
\end{enumerate}

\begin{quote}
There is weak or little evidence against the null hypothesis - but the researchers should be advised to provide the actual P-value, not just P \textgreater{} 0.05.
\end{quote}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  `ns' indicating not significant
\end{enumerate}

\begin{quote}
Traditionally, `ns' stands for not significant (for the set level of significance mentioned in the study, usually 0.05). You might still come across this term in some journal articles but this is not best practice for most journals these days. Researchers should always state the P-value (not just whether or not it was significant).
\end{quote}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{3}
\tightlist
\item
  significant differences exist
\end{enumerate}

\begin{quote}
This would imply that the P-value is less than the set level of significance mentioned in the study (usually, 0.05). As such, we would conclude that there was evidence against the null hypothesis. However, the researchers should be advised to always state the P-value (not just whether or not it was significant).
\end{quote}

\hypertarget{activity-4.2}{%
\subsection*{Activity 4.2}\label{activity-4.2}}
\addcontentsline{toc}{subsection}{Activity 4.2}

For the following hypothetical situations, formulate the null hypothesis and alternative hypothesis and write a conclusion about the study results:

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
  A study was conducted to investigate whether the mean systolic blood pressure of males aged 40 to 60 years was different to the mean systolic blood pressure of females aged 40 to 60 years. The result of the study was that the mean systolic blood pressure was higher in males by 5.1 mmHg (95\% CI 2.4 to 7.6; P = 0.008).
\end{enumerate}

\begin{quote}
H\textsubscript{0}: There is no difference in the mean systolic blood pressure between males aged 40-60 years and females aged 40-60 years.
\end{quote}

\begin{quote}
H\textsubscript{A}: There is a difference in the mean systolic blood pressure between males aged 40-60 years and females aged 40 to 60 years.
\end{quote}

\begin{quote}
Conclusion: The mean SBP was 5.1 mmHg (95\% CI: 2.4 to 7.6 mmHg) higher in males aged 40-60 years compared to females aged 40-60 years. The P value is 0.008 which provides strong evidence against the null hypothesis. Therefore, we can conclude that there is a difference in the mean SBP of males and females aged 40-60 years.
\end{quote}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  A case-control study was conducted to investigate the association between obesity and breast cancer. The researchers found an OR of 3.21 (95\% CI 1.15 to 8.47; P = 0.03).
\end{enumerate}

\begin{quote}
H\textsubscript{0}: There is no association between obesity and breast cancer.
{[}A more formal way of saying this is that there is no difference in the odds of exposure to obesity among cases of breast cancer and controls i.e.~OR = 1{]}.
\end{quote}

\begin{quote}
H\textsubscript{A}: There is an association between obesity and breast cancer.
{[}A more formal way of saying this is that there is a difference in the odds of exposure to obesity among cases and controls i.e.~OR ≠ 1{]}.
\end{quote}

\begin{quote}
Conclusion: The odds ratio is estimated as 3.21, indicating a positive association between the study factor of obesity and the outcome of breast cancer. The 95\% CI is 1.15 to 8.47 and excludes the null value of no association (i.e.~OR = 1). The P value is 0.03 which provides evidence against the null hypothesis. Therefore, we can conclude that there is a positive association between obesity and breast cancer.
\end{quote}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  A cohort study investigated the relationship between eating a healthy diet and the incidence of influenza infection among adults aged 20 to 60 years. The results were RR = 0.88 (95\% CI 0.65 to 1.50; P = 0.2).
\end{enumerate}

\begin{quote}
H\textsubscript{0}: There is no association between influenza infection and a healthy diet among adults aged 20-60 years.
{[}A more formal way of saying this is that there is no difference in the risk of influenza infection among adults aged 20-60 years who have a healthy diet compared to those who do not have a healthy diet. i.e.~RR = 1{]}.
\end{quote}

\begin{quote}
H\textsubscript{A}: There is an association between influenza infection and a healthy diet among adults aged 20-60 years.
{[}A more formal way of saying this is that there is a difference in the risk of influenza infection among adults aged 20-60 years who have a healthy diet compared to those who do not have a healthy diet. i.e.~RR ≠ 1{]}.
\end{quote}

\begin{quote}
Conclusion: The relative risk is estimated as 0.88, indicating a protective association between the study factor of healthy diet and the outcome factor of influenza infection among adults aged 20 to 60 years. However, the 95\% confidence interval includes the null value of 1.0 (no association). The P value is 0.2, which means there is no evidence against the null hypothesis. Thus, we can conclude that there is no evidence of an association between a healthy diet and influenza infection among adults aged 20 to 60 years.
\end{quote}

\hypertarget{activity-4.3}{%
\subsection*{Activity 4.3}\label{activity-4.3}}
\addcontentsline{toc}{subsection}{Activity 4.3}

A pilot study was conducted to compare the mean daily energy intake of women aged 25 to 30 years with the recommended intake of 7750 kJ/day. In this study, the average daily energy intake over 10 days was recorded for 12 healthy women of that age group. The data are in the Excel file Activity\_4.3.xls. Import the file into R for this activity.

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
  State the research question
\end{enumerate}

\begin{quote}
Is the mean daily energy intake of women aged 25-30 years different to the recommended daily intake of 7750 kJ/day?
\end{quote}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  Formulate the null hypothesis
\end{enumerate}

\begin{quote}
H\textsubscript{0}: the mean daily energy intake of women aged 25-30 years is the same as the recommended daily intake of 7750 kJ/day.
\end{quote}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  Formulate the alternative hypothesis
\end{enumerate}

\begin{quote}
H\textsubscript{A}: the mean daily energy intake of women aged 25-30 years is not same as the recommended daily intake of 7750 kJ/day.
\end{quote}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{3}
\tightlist
\item
  Analyse the data and report your conclusions
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(readxl)}
\FunctionTok{library}\NormalTok{(jmv)}

\NormalTok{pilot }\OtherTok{\textless{}{-}} \FunctionTok{read\_excel}\NormalTok{(}\StringTok{"data/activities/Activity\_S4.3.xls"}\NormalTok{)}
\FunctionTok{summary}\NormalTok{(pilot)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      Energy    
##  Min.   :5260  
##  1st Qu.:6045  
##  Median :6674  
##  Mean   :6856  
##  3rd Qu.:7642  
##  Max.   :8770
\end{verbatim}

\begin{quote}
As we are comparing a continuous distribution to a hypothesised mean, we will use a one-sample t-test to conduct this analysis. As the one-sample t-test assumes our data follow a Normal distribution, we should assess this using a histogram.
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{hist}\NormalTok{(pilot}\SpecialCharTok{$}\NormalTok{Energy, }\AttributeTok{main=}\StringTok{"Daily energy intake of pilot participants"}\NormalTok{, }\AttributeTok{xlab=}\StringTok{"Energy (kJ)"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{phcm9795-solutions-R_files/figure-latex/unnamed-chunk-44-1.pdf}

\begin{quote}
It is very difficult to assess the shape of a distribution with only 12 observations, but here we can see that the distribution looks roughly symmetric. In this case, we will assume Normality.
\end{quote}

\begin{quote}
The one-sample t-test is conducted as below, to compare the variable Energy to the hypothesised mean of 7750 kJ/day:
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t.test}\NormalTok{(pilot}\SpecialCharTok{$}\NormalTok{Energy, }\AttributeTok{mu=}\DecValTok{7750}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  One Sample t-test
## 
## data:  pilot$Energy
## t = -2.7141, df = 11, p-value = 0.02014
## alternative hypothesis: true mean is not equal to 7750
## 95 percent confidence interval:
##  6131.023 7580.977
## sample estimates:
## mean of x 
##      6856
\end{verbatim}

\begin{quote}
The one-sample t-test output shows that the mean daily energy intake of the 12 women is 6856 kJ (95\% CI: 6131 to 7581 kJ). There is evidence (t = −2.71 with 11 DF, P = 0.02) that the mean daily energy intake of women aged 25-30 years is lower than the recommended daily intake of 7750 kJ/day.
\end{quote}

\hypertarget{activity-4.4}{%
\subsection*{Activity 4.4}\label{activity-4.4}}
\addcontentsline{toc}{subsection}{Activity 4.4}

Which procedure gives the researcher the better chance of rejecting a null hypothesis?

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
  comparing the data-based p-value with the level of significance at 5\%
\item
  comparing the 95\% CI with a nominated value
\item
  neither procedure
\end{enumerate}

\begin{quote}
Both `a' and `b' would give the same chance to reject the null hypothesis. This is because both `a' and `b' are giving you the same information in a different way. In `a' you will get the probability of observing the difference you see in your data by chance and if it is \textless0.05 you will reject the null hypothesis at the 5\% level. Whereas in `b' you will see whether the null value (value of no difference) lies within the range which you are 95\% confident contains the true value. If the null value falls outside the 95\% CI, you would have less than 5\% (100-95 = 5\%) probability seeing the observed difference in your data if there were no difference.
\end{quote}

\hypertarget{activity-4.5}{%
\subsection*{Activity 4.5}\label{activity-4.5}}
\addcontentsline{toc}{subsection}{Activity 4.5}

Setting the significance level at P \textless{} 0.10 instead of the more usual P \textless{} 0.05 increases the likelihood of:

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
  a Type I error
\item
  a Type II error
\item
  rejecting the null hypothesis
\item
  Not rejecting the null hypothesis
\end{enumerate}

\begin{quote}
Setting the significance level cut-off at 0.10 instead of the more usual 0.05 increases the likelihood of
\textbf{a. a Type I error} and \textbf{c.~rejecting the null hypothesis}.
\end{quote}

\begin{quote}
The cut-off of 0.10 increases the chance of a type I error from 5\% to 10\% (the chance of making a Type I error is the same as the significance level). If the significance level is higher, then there higher probability of rejecting the null hypothesis if there no effect in reality.
\end{quote}

\hypertarget{activity-4.6}{%
\subsection*{Activity 4.6}\label{activity-4.6}}
\addcontentsline{toc}{subsection}{Activity 4.6}

For a fixed sample size setting the significance level at a very extreme cut-off such as P \textless{} 0.001 increases the chances of:

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
  obtaining a significant result
\item
  rejecting the null hypothesis
\item
  a Type I error
\item
  a Type II error
\end{enumerate}

\begin{quote}
Setting the significance level at a very extreme cut-off (such as 0.001) increases the chances of: \textbf{d.~a Type II error}.
\end{quote}

\begin{quote}
For a given sample, if the significance level is set very small it will make it harder to find evidence against the null hypothesis. In other words, it will be difficult to detect an effect if an effect exists in reality. In other words, the probability of type II error will increase: you will not be able to reject the null hypothesis when a real difference exists.
\end{quote}

\hypertarget{module-4-full-script}{%
\chapter*{Module 4: Full script}\label{module-4-full-script}}
\addcontentsline{toc}{chapter}{Module 4: Full script}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Author: Timothy Dobbins}
\CommentTok{\# Date: June, 2022}
\CommentTok{\# Purpose: Learning activities for Module 4}

\FunctionTok{library}\NormalTok{(readxl)}
\FunctionTok{library}\NormalTok{(jmv)}

\NormalTok{pilot }\OtherTok{\textless{}{-}} \FunctionTok{read\_excel}\NormalTok{(}\StringTok{"data/activities/Activity\_S4.3.xls"}\NormalTok{)}
\FunctionTok{hist}\NormalTok{(pilot}\SpecialCharTok{$}\NormalTok{Energy, }\AttributeTok{main=}\StringTok{"Daily energy intake of pilot participants"}\NormalTok{, }\AttributeTok{xlab=}\StringTok{"Energy (kJ)"}\NormalTok{)}

\FunctionTok{descriptives}\NormalTok{(pilot)}

\FunctionTok{t.test}\NormalTok{(pilot}\SpecialCharTok{$}\NormalTok{Energy, }\AttributeTok{mu=}\DecValTok{7750}\NormalTok{)}
\end{Highlighting}
\end{Shaded}


\end{document}
